### ISSUE TITLE
Track Android version distribution

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#426]
Values fetched from:  http://developer.android.com/about/dashboards/index.html

<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th></tr>
<tr><td>1.6</td><td>Donut</td><td>4</td><td>0.1%</td></tr>
<tr><td>2.1</td><td>Eclair</td><td>7</td><td>1.5%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>3.2%</td></tr>
<tr><td>2.3 - 2.3.2</td><td>Gingerbread</td><td>9</td><td>0.1%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td></td><td>10</td><td>36.4%</td></tr>
<tr><td>3.2</td><td>Honeycomb</td><td>13</td><td>0.1%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>25.6%</td></tr>
<tr><td>4.1.x</td><td>Jelly Bean</td><td>16</td><td>29.0%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>4.0%</td></tr>
</table>

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>5.0</td><td>Lollipop</td><td>21</td><td>1.6%</td><td>1.6%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>39.7%</td><td>41.3%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>6.3%</td><td>47.6%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>19.8%</td><td>67.4%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>18.4%</td><td>85.8%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>6.4%</td><td>92.2%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>7.4%</td><td>99.6%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.4%</td><td>100%</td></tr>
</table>

Data collected during a 7-day period ending on February 2, 2015. 

![chart](https://cloud.githubusercontent.com/assets/57275/6426721/56e26764-bf69-11e4-945c-872bab7a845e.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>5.0</td><td>Lollipop</td><td>21</td><td>3.3%</td><td>3.3%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>40.9%</td><td>44.2%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>5.9%</td><td>50.1%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>19.4%</td><td>69.5%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>17.3%</td><td>86.8%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>5.9%</td><td>92.7%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>6.9%</td><td>99.6%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.4%</td><td>100%</td></tr>
</table>

Data collected during a 7-day period ending on March 2, 2015. 

![chart](https://cloud.githubusercontent.com/assets/57275/6650949/6b82c4b0-ca2d-11e4-8d26-32966cf29b36.png)

**Comment by daneb** [comment]
Hi Uwe

What are the numbers? That is - how many devices are we looking at?

Thanks
Dane

On Sat, Mar 14, 2015 at 10:39 AM, Uwe Kubosch <notifications@github.com>
wrote:

>  Version Codename API Distribution Cumulative  5.0 Lollipop 21 3.3% 3.3%
> 4.4 KitKat 19 40.9% 44.2%  4.3 Jelly Bean 18 5.9% 50.1%  4.2.x 17 19.4%
> 69.5%  4.1.x 16 17.3% 86.8%  4.0.3 - 4.0.4 Ice Cream Sandwich 15 5.9%
> 92.7%  2.3.3 - 2.3.7 Gingerbread 10 6.9% 99.6%  2.2 Froyo 8 0.4% 100%
>
> Data collected during a 7-day period ending on March 2, 2015.
>
> [image: chart]
> <https://cloud.githubusercontent.com/assets/57275/6650949/6b82c4b0-ca2d-11e4-8d26-32966cf29b36.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruboto/ruboto/issues/426#issuecomment-80154401>.
>



-- 

±± http://www.codedtrue.com ±±

**Comment by donv** [comment]
Hi @daneb !

I just collect the numbers from http://developer.android.com/about/dashboards/index.html

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>0.4%</td><td>0.4%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>5.0%</td><td>5.4%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>41.4%</td><td>46.8%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>5.6%</td><td>52.4%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>18.6%</td><td>71.0%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>16.5%</td><td>87.5%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>5.7%</td><td>93.2%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>6.4%</td><td>99.6%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.4%</td><td>100%</td></tr>
</table>
Data collected during a 7-day period ending on April 6, 2015. 
![chart](https://cloud.githubusercontent.com/assets/57275/7221675/c6b52b3c-e6f4-11e4-9f7e-f9b992b804d2.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>0.8%</td><td>0.8%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>11.6%</td><td>12.4%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>39.2%</td><td>51.6%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>5.2%</td><td>56.8%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>17.5%</td><td>74.3%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>14.7%</td><td>89.0%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>5.1%</td><td>94.1%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>5.6%</td><td>99.7%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.3%</td><td>100%</td></tr>
</table>
Data collected during a 7-day period ending on June 1, 2015. 
![chart](https://cloud.githubusercontent.com/assets/57275/8039684/bdf9000c-0e0b-11e5-8809-048d675bfa7d.png)

**Comment by danielpassos** [comment]
@donv This issue is really necessary? Why you want to track it?

**Comment by donv** [comment]
These historic values used to be available form Google and are useful to see trends in the distribution of Android versions.

Our code contains lots for checks for which version of android is supported, and we can benefit from not supporting older versions since it will make our code simpler.

These numbers can help us decide if we can drop support for an older version not only based on its current use, but also on the trend the last months.

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>2.6%</td><td>2.6%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>15.5%</td><td>18.1%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>39.3%</td><td>57.4%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>4.7%</td><td>62.1%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>15.9%</td><td>78.0%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>13.0%</td><td>91.0%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>4.1%</td><td>95.1%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>4.6%</td><td>99.7%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.3%</td><td>100%</td></tr>
</table>
Data collected during a 7-day period ending on August 3, 2015.
![chart](https://cloud.githubusercontent.com/assets/57275/9677107/046e7bb6-52d6-11e5-86b7-c5ca7e11ef6e.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>7.9%</td><td>7.9%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>15.6%</td><td>23.5%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>38.9%</td><td>62.4%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>4.3%</td><td>67.7%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>14.5%</td><td>81.2%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>11.4%</td><td>92.6%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>3.4%</td><td>96.0%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>3.8%</td><td>99.8%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.2%</td><td>100%</td></tr>
</table>
Data collected during a 7-day period ending on October 5, 2015. 

![chart](https://cloud.githubusercontent.com/assets/57275/10498480/da02841a-72cb-11e5-9357-2e7171616b23.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>6.0</td><td>Marshmallow</td><td>23</td><td>0.3%</td><td>0.3%</td></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>10.1%</td><td>10.4%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>15.5%</td><td>25.9%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>37.8%</td><td>63.7%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>4.1%</td><td>67.8%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>13.9%</td><td>81.7%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>11.0%</td><td>92.7%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>3.3%</td><td>96.0%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>3.8%</td><td>99.8%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.2%</td><td>100%</td></tr>
</table>
Data collected during a 7-day period ending on November 2, 2015. 

![chart](https://cloud.githubusercontent.com/assets/57275/11183810/1a1d1f62-8c74-11e5-8ad3-10a607117943.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>6.0</td><td>Marshmallow</td><td>23</td><td>0.5%</td><td>0.5%</td></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>13.2%</td><td>13.7%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>16.3%</td><td>30.0%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>36.6%</td><td>66.6%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>3.9%</td><td>70.5%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>13.0%</td><td>83.5%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>10.0%</td><td>93.5%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>2.9%</td><td>96.4%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>3.4%</td><td>99.8%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.2%</td><td>100%</td></tr>
</table>
Data collected during a 7-day period ending on December 7, 2015. 

![chart](https://cloud.githubusercontent.com/assets/57275/11909281/de90d92c-a5e4-11e5-8d87-ee302e401060.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>6.0</td><td>Marshmallow</td><td>23</td><td>0.7%</td><td>0.5%</td></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>15.7%</td><td>13.7%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>16.9%</td><td>30.0%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>36.1%</td><td>66.6%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>3.5%</td><td>70.5%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>12.2%</td><td>83.5%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>9.0%</td><td>93.5%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>2.7%</td><td>96.4%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>3.0%</td><td>99.8%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.2%</td><td>100%</td></tr>
</table>
Data collected during a 7-day period ending on January 4, 2016.

![chart](https://cloud.githubusercontent.com/assets/57275/12480463/cd240f9c-c042-11e5-9e18-2648fe1b22ac.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>6.0</td><td>Marshmallow</td><td>23</td><td>1.2%</td><td>1.2%</td></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>17.1%</td><td>18.3%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>17.0%</td><td>35.3%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>35.5%</td><td>70.8%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>3.4%</td><td>74.2%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>11.7%</td><td>85.9%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>8.8%</td><td>94.7%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>2.5%</td><td>97.2%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>2.7%</td><td>99.9%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.1%</td><td>100%</td></tr>
</table>

Data collected during a 7-day period ending on February 1, 2016.

![chart](https://cloud.githubusercontent.com/assets/57275/13378234/59aaab1e-ddfe-11e5-8dc4-bab3c8a9039b.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>6.0</td><td>Marshmallow</td><td>23</td><td>7.5%</td><td>7.5%</td></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>19.4%</td><td>26.4%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>16.2%</td><td>43.1%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>32.5%</td><td>75.6%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>2.9%</td><td>78.5%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>10.0%</td><td>88.5%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>7.2%</td><td>95.7%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>2.0%</td><td>97.7%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>2.2%</td><td>99.9%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.1%</td><td>100%</td></tr>
</table>

Data collected during a 7-day period ending on May 2, 2016. 

![chart](https://cloud.githubusercontent.com/assets/57275/15082706/9d8de426-13c9-11e6-8594-8fbee0e12f84.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>6.0</td><td>Marshmallow</td><td>23</td><td>18.7%</td><td>18.7%</td></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>21.9%</td><td>40.6%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>13.1%</td><td>53.7%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>27.7%</td><td>81.4%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>2.3%</td><td>83.7%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>7.7%</td><td>91.4%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>5.6%</td><td>97.0%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>1.4%</td><td>98.4%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>1.5%</td><td>99.9%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.1%</td><td>100%</td></tr>
</table>

Data collected during a 7-day period ending on September 5, 2016.

![chart](https://cloud.githubusercontent.com/assets/57275/19129831/09c27174-8b49-11e6-8a71-cb4072693aa6.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>7.0</td><td>Nougat</td><td>24</td><td>0.3%</td><td>0.3%</td></tr>
<tr><td>6.0</td><td>Marshmallow</td><td>23</td><td>24.0%</td><td>24.3%</td></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>22.8%</td><td>47.1%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>11.3%</td><td>58.4%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>25.2%</td><td>83.6%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>2.0%</td><td>85.6%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>6.8%</td><td>92.4%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>4.9%</td><td>97.3%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>1.3%</td><td>98.6%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>1.3%</td><td>99.9%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.1%</td><td>100%</td></tr>
</table>

Data collected during a 7-day period ending on November 7, 2016.

![chart](https://cloud.githubusercontent.com/assets/57275/20327005/9942acda-ab8b-11e6-8a1c-0915e3d5777d.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>7.0</td><td>Nougat</td><td>24</td><td>0.4%</td><td>0.4%</td></tr>
<tr><td>6.0</td><td>Marshmallow</td><td>23</td><td>26.3%</td><td>26.7%</td></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>23.2%</td><td>49.9%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>10.8%</td><td>60.7%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>24.0%</td><td>84.7%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>1.9%</td><td>86.6%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>6.4%</td><td>94.0%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>4.5%</td><td>97.5%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>1.2%</td><td>98.7%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>1.2%</td><td>99.9%</td></tr>
<tr><td>2.2</td><td>Froyo</td><td>8</td><td>0.1%</td><td>100%</td></tr>
</table>

Data collected during a 7-day period ending on December 5, 2016. 

![chart](https://cloud.githubusercontent.com/assets/57275/21507963/32bdde9a-cc7d-11e6-9805-5d3f3b2a7208.png)

**Comment by donv** [comment]
<table>
<tr><th>Version</th><th>Codename</th><th>API</th><th>Distribution</th><th>Cumulative</th></tr>
<tr><td>7.1</td><td>Nougat</td><td>25</td><td>0.5%</td><td>0.5%</td></tr>
<tr><td>7.0</td><td></td><td>24</td><td>6.6%</td><td>7.1%</td></tr>
<tr><td>6.0</td><td>Marshmallow</td><td>23</td><td>31.2%</td><td>38.3%</td></tr>
<tr><td>5.1</td><td>Lollipop</td><td>22</td><td>23.3%</td><td>61.6%</td></tr>
<tr><td>5.0</td><td></td><td>21</td><td>8.7%</td><td>70.3%</td></tr>
<tr><td>4.4</td><td>KitKat</td><td>19</td><td>18.8%</td><td>89.1%</td></tr>
<tr><td>4.3</td><td>Jelly Bean</td><td>18</td><td>1.3%</td><td>90.4%</td></tr>
<tr><td>4.2.x</td><td></td><td>17</td><td>4.6%</td><td>95.0%</td></tr>
<tr><td>4.1.x</td><td></td><td>16</td><td>3.2%</td><td>98.2%</td></tr>
<tr><td>4.0.3 - 4.0.4</td><td>Ice Cream Sandwich</td><td>15</td><td>0.8%</td><td>99.0%</td></tr>
<tr><td>2.3.3 - 2.3.7</td><td>Gingerbread</td><td>10</td><td>1.0%</td><td>100%</td></tr>
</table>

Data collected during a 7-day period ending on May 2, 2017. 
Any versions with less than 0.1% distribution are not shown.

![chart](https://cloud.githubusercontent.com/assets/57275/25778965/147adc34-330d-11e7-836c-c909f1deac6c.png)

**Comment by donv** [comment]
Closing since we hopefully don't have to follow these versions as closely anymore.
