### ISSUE TITLE
Ruboto command not found after installation

### ISSUE THREAD

**Issue by nikhilbhardwaj** [ruboto/ruboto#555]
I am trying to install ruboto on mac os. I have jruby installed with rbenv.

~> ruby -v
jruby 1.7.8 (1.9.3p392) 2013-11-14 0ce429e on Java HotSpot(TM) 64-Bit Server VM 1.7.0_25-b15 [darwin-x86_64]

 ~> gem install bundler jruby-jars ruboto
Fetching: bundler-1.5.1.gem (100%)
Successfully installed bundler-1.5.1
Fetching: jruby-jars-1.7.9.gem (100%)
Successfully installed jruby-jars-1.7.9
Successfully installed ruboto-1.0.0
3 gems installed

 ~> ruboto setup
fish: Unknown command 'ruboto'

I have the other pre-requisites installed, is the procedure for installing ruboto 1.0 different from older versions?

**Comment by joeymetal** [comment]
https://edelivery.oracle.com/otn-pub/java/jdk/7/jdk-7-windows-x64.exe
this linkk not work 
ruby -S ruboto setup ou  ruboto setup 
 do you do not you have a private repository?

**Comment by donv** [comment]
Hi @joeymetal !

Please open a new issue for this.
