### ISSUE TITLE
ruboto emulator -t android-19 failed

### ISSUE THREAD

**Issue by amitach** [ruboto/ruboto#566]
No emulator is running.
Creating AVD Android_4.4
Valid ABIs: armeabi-v7a, x86
Failed to create AVD.

Its running for Android_4.2
ruboto gem version I am using is 1.01

Also,
ruboto setup -y -t 19
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Android SDK Command adb  : Found
Android SDK Command dx   : Found
Platform SDK android-19  : Found

```
*** Ruboto setup is OK! ***
```

How do I get it running?

**Comment by predatorian3** [comment]
I'm still having this issue with 
```
ruboto emulator -t android-19
```

**Comment by donv** [comment]
Hi @predatorian3!

Thanks for the report!  Could you open a new issue with your exact information?

**Comment by predatorian3** [comment]
My apologies, I forgot to update this. I figured out my issue was that the way I had installed it I didn't have permissions to create AVD's or run them with Ruboto. I had to instead download and place the Android SDK manager in my $HOME directory, and then run it from there. After that, I was able to do what I needed. If need be, I'll create a new issue concerning the wiki's instruction on this.
