### ISSUE TITLE
How can I help? (jaunesarmiento)

### ISSUE THREAD

**Issue by jaunesarmiento** [ruboto/ruboto#578]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:
I've played with the Android SDK for quite some time. But I'm more experienced in Ruby and I build iOS apps using RubyMotion.

My experience with HTML, CSS, JavaScript, and Jekyll:
I believe this can be answered in one GitHub repository, https://github.com/jaunesarmiento/fries. Its documentation runs on Jekyll (http://getfri.es)

My experience using git and GitHub:
I can say I'm a fairly advanced git user.

My other interests and passions:
I really love Android. :)

**Comment by donv** [comment]
Hi @jaunesarmiento and @rscottm !

I assume you have moved on from this issue :smile: 

Feel free to reopen or start a new issue if you still have plans for this.
