### ISSUE TITLE
How can I help? (bobquest33)

### ISSUE THREAD

**Issue by bobquest33** [ruboto/ruboto#581]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:
I have downloaded the ruboto on my nexus 4 and have played around with its features and am trying out to make a production app out of it.

My experience with HTML, CSS, JavaScript, and Jekyll:
Have 1 year of experience.

My experience using git and GitHub:
Have over 2 Years of experience

My other interests and passions:
Node js, testing, capybara, C++, shell scripting, mongo db and groovy

**Comment by donv** [comment]
Hi @bobquest33 !

Have you tried any more Ruboto development?  Feel free to contact us if you have any questions or need help in any way.
