### ISSUE TITLE
How can I help? (devaroop)

### ISSUE THREAD

**Issue by devaroop** [ruboto/ruboto#589]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto: Ruby - full, Android  - only debugging with 'adb'

My experience with HTML, CSS, JavaScript, and Jekyll: Proficient with HTML, CSS and JS

My experience using git and GitHub: Full

My other interests and passions: Love coding and knowing new things

**Comment by donv** [comment]
Hi @devaroop !

Sorry for not getting back to you earlier.  How is your Ruboto development coming along?

**Comment by danielpassos** [comment]
Hi,

Since this issue does not has any activity for a long time, I'm closing it. Feel free to reopen it or ping me in the specific issue you have interesting in work on.
