### ISSUE TITLE
Cannot open apk in emulator 

### ISSUE THREAD

**Issue by sid-arora** [ruboto/ruboto#590]
Continuing from issue 585 : https://github.com/ruboto/ruboto/issues/585

The build is now successful and triggered in the emulator. It prompts me to install ruboto-core-release.apk. On clicking the image, it downloads the apk file. But on clicking the file, It says "Cannot open file"

**Comment by donv** [comment]
Hi @sid-arora !

I am assuming you have moved on from this :)  Feel free to reopen or contact us in any way if you need help.
