### ISSUE TITLE
ruby version problem

### ISSUE THREAD

**Issue by pynixwang** [ruboto/ruboto#631]
I set ruby version to 2.0 and the app starts the get ruboto core activity, and it works when I comment it in ruboto.yml.

--with-jruby and 2.0 the same with above.

and I don't know how to debug.

**Comment by donv** [comment]
Hi @pynixwang !

Sorry for not getting back to you earlier.  Did you solve your problem?

**Comment by pynixwang** [comment]
@donv

sorry, I 'm do something other,maybe I can 't back. really sorry.

**Comment by donv** [comment]
No problem.  Thanks for reporting the problem.
