### ISSUE TITLE
Can't add jar files to proyect. Can't start the proyect with jars added

### ISSUE THREAD

**Issue by IgorJorobus** [ruboto/ruboto#634]
Hi, how are you? This is my system:

 Windows 7 x64, Ruby 2.0, Ruboto 1.1.1 

 I have NO jruby installed. I'm having some issues trying to include jars files inside my app. First of all I can't start my project with jars included. I try with:

`ruboto gen app --package="some.package.example" --ruby-version="2.0" --target="android-15" --with-jruby`
#=> (Malformed version number string true (ArgumentError))

 Okay, now I try with entering the last jruby-jars version explicitly:

`ruboto gen app --package="some.package.example" --ruby-version="2.0" --target="android-15" --with-jruby="1.7.13"`

 ...all goes fine until this:

```
`Removing unneeded classes from jruby-core-1.7.13.jar...exclude pattern "**/*Windows*" found no files...exclude pattern "jnr/constants/platfo
rm/darwin" found no files...javac: invalid flag: (x86)\Android\android-sdk\platforms\android-15\android.jar
Usage: javac <options> <source files>
use -help for a list of possible options
F, [2014-07-02T19:48:04.175702 #15156] FATAL -- : Compile failed (RuntimeError)
C:/Ruby200/lib/ruby/gems/2.0.0/gems/ruboto-1.1.1/lib/ruboto/util/update.rb:570:in block (3 levels) in reconfigure_jruby_core'
#.....keeps going the trace`
```

 I've started the project without the "--with-jruby" directive, trying to add them after. I've tried:

`ruboto update jruby --force`

...and stuck with the same respone than above. Also tried:

`ruboto gen jruby`

 Same thing. Do not what else do.

**Comment by donv** [comment]
Hi @IgorJorobus !

Sorry for the very late reply!  I am releasing Ruboto 1.3.0 later today.  Could you try it and see if it works for you?

**Comment by viniciusgati** [comment]
same for 1.3.1-dev

**Comment by donv** [comment]
Hi @IgorJorobus !

Thanks for the report.  This looks like a problem with a space in the path.  You android tools are probably installed in a directory with a space, and some command is missing some quotes.

Does this sound like something you could investigate?

@CaptainJet could you perhaps look at this?

**Comment by IgorJorobus** [comment]
Honestly I'm a bit bussy right now, can't promess when, sorry donv.

**Comment by donv** [comment]
Closing this for now.  Please open a new issue if you encounter this (or another) problem.
