### ISSUE TITLE
Gosu example is not working

### ISSUE THREAD

**Issue by IgorJorobus** [ruboto/ruboto#635]
Hi, it's me again. My system:

 Windows 7 x64, Ruby 2.0, Ruboto 1.1.1

I can't put to work the gosu example, I've tried many many ways. I've followed the advices by Ruboto team, I've follow the advices of Geroe(maker of gosu_android), and nothing. Basically what Ruboto tell me when I do `rake`(to generate an *.apk file and test it on my Smartphone) is(I'll put just important things):

`Increasing max heap space from 1024M to 2048M in C:/Program Files (x86)/Android/android-sdk/build-tools/20.0.0/dx.bat

!!! Unable to increase dx heap size !!!

Generating D:/Android/tutorial_touch/libs/bundle.jar
Fetching gem metadata from https://www.rubygems.org/............
Fetching additional metadata from https://www.rubygems.org/..
Resolving dependencies...
Using gosu_android 0.0.5
Using bundler 1.6.2
rake aborted!
Gem path not found
D:/Android/tutorial_touch/rakelib/ruboto.rake:691:in block in <top (required)>'
Tasks: TOP => default => debug => D:/Android/tutorial_touch/bin/TutorialTouch-debug.apk => D:/Android/tutorial_touch/libs/bundle.jar
(See full trace by running task with --trace)'`

 So I've been sneaking the Ruboto code, and generated the folder gems under bin/bundler manually, so it compiles, but the game doesn't work(of course), and I see nothing inside this folder "gems". I've tried many differents ways but always crash with the same. When I followed up the advices by Geroe same thing happens. One thing to note is that I made work the "Quick Start" example in my Smartphone and emulator, but not gosu example. Also when I do `gosu_android --add` and create the dir "gems" manually and compile the *.apk weight 6 more times than if I not use `gosu_android --add`. I'm aware that the comand place a file inside "libs" folder. I'm a bit frustrated with this. After this I though that perhaps was something about the jars files missing, I tried to add them, but can't(see my other post).

**Comment by donv** [comment]
Hi!

Any progress on this?

**Comment by IgorJorobus** [comment]
Hi donv, honestly I never tried again. I'm going to take a look at this issue this weekend.

**Comment by IgorJorobus** [comment]
Working with the current version.

**Comment by donv** [comment]
Great!
