### ISSUE TITLE
Extra installs to build on Ubuntu 64 bit

### ISSUE THREAD

**Issue by rscottm** [ruboto/ruboto#638]
Setting up a new build environment on Ubuntu 14.04 (64 bit). Tried to build a ruboto app and got an error running aapt (no such file or directory). This fixed the problem:

http://stackoverflow.com/questions/22701405/aapt-ioexception-error-2-no-such-file-or-directory-why-cant-i-build-my-grad

sudo apt-get install lib32stdc++6
sudo apt-get install lib32z1

**Comment by donv** [comment]
We could definitely identify some common distros and install the needed packages there.

Anyone want to work on this?

**Comment by donv** [comment]
I believe Ubuntu 64 bit is pretty common now, and we can rely on new reports to get things working.  Closing this.  Open new issues for setup on Ubuntu 64 bit if you have any.
