### ISSUE TITLE
How can I help? (sg552)

### ISSUE THREAD

**Issue by sg552** [ruboto/ruboto#640]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:
2005~ 2008  Java
2009~ now:  Ruby .
No Android nor Ruboto exp, currently.

My experience with HTML, CSS, JavaScript, and Jekyll:
Master CSS, HTML.  Have 4 years of JavaScript.  Don't know Jekyll. 

My experience using git and GitHub:
Familiar with most of Git operations. (pull , push, merge, rebase... )

My other interests and passions:
Web developer, using Ruby. Dislike hard-to-read programming languages ( php, java, c++, etc )  working in Beijing, want to do something for Robutu( do you need Chinese translation for Robutu guide? )

**Comment by donv** [comment]
Hi @sg552 !

How are you doing?  Have you tried any of the Ruboto tutorials?

**Comment by sg552** [comment]
hi @donv 
  I am sorry, I just setup the Ruboto environment, but failed to implement an App , because I didn't find any guide ( like http://guides.rubyonrails.org ) .
  From Oct , 2014  , I chose Titanium to develop mobile apps.  
  So I don't think there's chance to use Ruboto in my team. Should I close this issue?
