### ISSUE TITLE
How can I help? (arantessergio)

### ISSUE THREAD

**Issue by arantessergio** [ruboto/ruboto#651]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:

My experience with HTML, CSS, JavaScript, and Jekyll:

My experience using git and GitHub:

My other interests and passions:

**Comment by donv** [comment]
Hi @arantessergio !

Have you tried any of the tutorials?

**Comment by danielpassos** [comment]
Hi @arantessergio are you interesting or playing with any specific issue?

**Comment by danielpassos** [comment]
Hi,

Since this issue does not has any activity for a long time, I'm closing it. Feel free to reopen it or ping me in the specific issue you have interesting in work on.
