### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by bennythejudge** [ruboto/ruboto#659]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:
I have studied Java but have no commercial experience.
I am studying Rails, I know enough Ruby but no commercial experience.
I have experience of coding in Perl and Python for system administration, automation and monitoring.

My experience with HTML, CSS, JavaScript, and Jekyll:
I have been studying web programming for several years and I have a good knowledge of html/css/js but no commercial experience. 
I am new to jekyll.

My experience using git and GitHub:
I use git for my own projects and at work. I am relatively new to github, I have recently started using it.
Prior to git, I have been a subversion user for several years.

My other interests and passions:
Rails mostly. Python. Monitoring.

**Comment by donv** [comment]
Hi @bennythejudge !

Sorry for the very late reply.  Have you tried any of the Ruboto tutorials?

**Comment by danielpassos** [comment]
Hi @bennythejudge are you interesting or playing with any specific issue?

**Comment by danielpassos** [comment]
Hi,

Since this issue does not has any activity for a long time, I'm closing it. Feel free to reopen it or ping me in the specific issue you have interesting in work on.
