### ISSUE TITLE
How can I help? (aripoya)

### ISSUE THREAD

**Issue by aripoya** [ruboto/ruboto#662]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto: Ruby

My experience with HTML, CSS, JavaScript, and Jekyll: JavaScript

My experience using git and GitHub:

My other interests and passions: education

**Comment by donv** [comment]
Hi @aripoya !

Did you try any of the tutorials?

**Comment by danielpassos** [comment]
Hi @aripoya are you interesting or playing with any specific issue?

**Comment by danielpassos** [comment]
Hi,

Since this issue does not has any activity for a long time, I'm closing it. Feel free to reopen it or ping me in the specific issue you have interesting in work on.
