### ISSUE TITLE
Bundler can't see personal gems/Locally installed gems do not get put on projects(only global).

### ISSUE THREAD

**Issue by pmpbar** [ruboto/ruboto#664]
@donv Didn't know how to really explain this but I think you know what I mean.

**Comment by donv** [comment]
Hi @pmpbar !

Sorry for the late reply.  This feature has now been added to Ruboto 1.3.0 due later today.  See https://github.com/ruboto/ruboto/issues/696 .  Could you try it and see if it works for you?

**Comment by pmpbar** [comment]
I need to set up another folder. I'll try it in the next week or so.

**Comment by donv** [comment]
Hi @pmpbar !

Did you try it with a newer release?

**Comment by donv** [comment]
Marking this as fixed.  Please open a new issue if you still have problems.

**Comment by pmpbar** [comment]
Sorry about the late reply! I haven't been able to test this but @donv I will make sure to let you know if I see the issue crop up again.

**Comment by donv** [comment]
Great @pmpbar !  Hoping to hear from you about anything Ruboto :smile:
