### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by gvaresh** [ruboto/ruboto#665]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:

My experience with HTML, CSS, JavaScript, and Jekyll:

My experience using git and GitHub:

My other interests and passions:

**Comment by donv** [comment]
Hi @gvaresh !

Sorry for the late reply!

The first step for new contributors is to install Ruboto and try some of the tutorials.  Can you do that?

**Comment by danielpassos** [comment]
Hi @gvaresh are you interesting or playing with any specific issue?

**Comment by danielpassos** [comment]
Hi,

Since this issue does not has any activity for a long time, I'm closing it. Feel free to reopen it or ping me in the specific issue you have interesting in work on.

**Comment by gvaresh** [comment]
ok . thanks
