### ISSUE TITLE
Keep on restarting new emulator

### ISSUE THREAD

**Issue by lobida** [ruboto/ruboto#669]
ruboto version 1.1.2 platform ubuntu 14.04
when I run: ruboto emulator -t android-19 -s
there's following output:

No emulator is running.
Start emulator without snapshot

Unable to start the emulator.
Start emulator without snapshot

Unable to start the emulator.
Start emulator without snapshot

Unable to start the emulator.
Start emulator without snapshot

and actually the emulator was starting and ruboto keep on starting new emulators, I have to canceled my command

**Comment by donv** [comment]
Hi @lobida @DHFE and @niamster !

Did you solve this problem?  I am releasing Ruboto 1.3.0 later today.  Could you try with that and see if it works for you?

**Comment by donv** [comment]
I believe this has been fixed in the upcoming 1.3.2 release.  Please open a new issue if you still have problems.
