### ISSUE TITLE
emulator

### ISSUE THREAD

**Issue by DHFE** [ruboto/ruboto#670]
I have a little problem, I'm trying to run an emulator on linux but I can't do it. I received this message
PANIC: Could not open

i use this command:
emulator -avd gingerbread

**Comment by donv** [comment]
Hi @DHFE !

Did you get the emulator going?  Did you try the "ruboto emulator" command?

**Comment by danielpassos** [comment]
Hey @DHFE Have you tried the @donv suggestion?

**Comment by donv** [comment]
No response for over a year, so closing :smile:
