### ISSUE TITLE
Warning after ruboto setup

### ISSUE THREAD

**Issue by xecutioner** [ruboto/ruboto#681]
WARN: Unresolved specs during Gem::Specification.reset:
      rake (~> 10.0)
      rubyzip (~> 1.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

**Comment by donv** [comment]
Hi @xecutioner !

This is a warning from RubyGems.  I am not sure why it happens, but it is not directly related to Ruboto.  It happens with many other projects as well.

I am not sure how to deal with the warning, and it does work, just a bit annoying.

Closing this issue for now.  Please comment if you have any insight in how to handle this.
