### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by ebruner** [ruboto/ruboto#683]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:
13 years java application development
a few years of rails
I'm trying out ruboto

My experience with HTML, CSS, JavaScript:

My experience using git and GitHub:

My other interests and passions:

**Comment by donv** [comment]
Hi @ebruner !

Have you tried any of the Ruboto tutorials?

**Comment by danielpassos** [comment]
Hey @ebruner are you interesting in any specific issue?

**Comment by danielpassos** [comment]
Hi,

Since this issue does not has any activity for a long time, I'm closing it. Feel free to reopen it or ping me in the specific issue you have interesting in work on.
