### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by StoRRica** [ruboto/ruboto#684]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:
I am ruby newbie, made few apps in school and with ruboto played for a while.

My experience with HTML, CSS, JavaScript, and Jekyll:

My experience using git and GitHub:
mainly with school projects
My other interests and passions:
I woul like to contribute to your project and also need to find a gem to contribute to so I cas pass my school subject

**Comment by donv** [comment]
Hi @StoRRica !

Cool that you want to contribute!

Have you completed any of the tutorials?

**Comment by StoRRica** [comment]
Not yet but looking forward to it. My plans are to have some before end of next week.

**Comment by StoRRica** [comment]
Hello @donv,
I meant to write you earlier, but i couldn't managed that because all of the exams I had. I have finished most of those tutorials you hav out there, but unfortunetly could't run those with JRuby with this error
ruboto gen app -t 15 --package org.ruboto.test --with-jruby
(Malformed version number string true (ArgumentError))
same error aplies when i try -t 19 or no type at all.
I also noticed that you want to build face recognition app using ruboto #693 . It is a nice idea, but FaceDetector api od Camera.Face will only give you a position of the face so you need to aply some kind of face recognition algorithm such as "trivial" PCA. I would recomend to use OpenCV for Android for such purpouse. This library also contains better face detector based on Haar like features.
My question is how can i help?
Thanks 
Michal

**Comment by donv** [comment]
Hi @StoRRica !

Sorry for the late response.  Busy with a new release coming later today.  Could you add your comments for the Facial Recognition App to the #693 issue?

Could you also try the tutorials with JRuby with the new Ruboto 1.3.0 release later today?  I think it has been fixed there.

**Comment by danielpassos** [comment]
Hi @StoRRica are you interesting or working in any specific issue?

**Comment by danielpassos** [comment]
Hi,

Since this issue does not has any activity for a long time, I'm closing it. Feel free to reopen it or ping me in the specific issue you have interesting in work on.
