### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by jay2452** [ruboto/ruboto#685]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:  Ruby and Java - 1 year

My experience with HTML, CSS, JavaScript, and Jekyll: HTML and CSS - 2 years

My experience using git and GitHub:  started using

My other interests and passions: programming

**Comment by donv** [comment]
Hi @jay2452 !

Good to have you with us!

The first step is to install Ruboto and complete a few of the tutorials.  Please ask questions while you do so and report your progress.

**Comment by donv** [comment]
Hi @jay2452 !

Have you tried any of the Ruboto tutorials?

**Comment by danielpassos** [comment]
@jay2452 are you interesting in any specific issue?

**Comment by danielpassos** [comment]
Hi,

Since this issue does not has any activity for a long time, I'm closing it. Feel free to reopen it or ping me in the specific issue you have interesting in work on.
