### ISSUE TITLE
Drop support for Android 2.3 api level 10

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#687]
Gingerbread has only 7.8% of the market and we don't know any devices that can run Ruboto with acceptable speed.

Please comment if you disagree.

**Comment by donv** [comment]
Anyone want to contribute to keeping Android 2.3 api level 10 support?  Else it will be removed in Ruboto 1.3.1.

**Comment by danielpassos** [comment]
@donv +1 to remove support for api level < 16

**Comment by donv** [comment]
Done!  Support for Android 2.3 dropped!  This means we also drop support for Android 3.x since there are no current devices running that.  Usage of Android 2.3 is 3.4%.

We will keep support for Android 4.0.3 api level 15 for a while since I have a customer with tablets using 4.0.3 still.
