### ISSUE TITLE
Set Android 4.1 api level 16 as default api level for new apps

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#688]
This still covers over 85% of the market and avoids important bugs in Android 4.0.3.

**Comment by danielpassos** [comment]
Is it done, right? I've just created a new app and ..

`<uses-sdk android:minSdkVersion='16' android:targetSdkVersion='16'/>`

**Comment by donv** [comment]
Yeah @danielpassos , it is done.  Just forgot to update the ticket.  Closing it for the 1.3.2 release so it is announced properly.
