### ISSUE TITLE
--with-jruby argument not working correctly

### ISSUE THREAD

**Issue by awernick** [ruboto/ruboto#692]
In an attempt to build a Ruboto app with the Jruby jars included in the apk, I tried initializing the project with the `--with-jruby` flag. 

When executing the following command `ruboto gen app --package com.test.testing --name testing --target 19 --activity MainActivity --with-jruby`, Ruboto  throws the error `(Malformed version number string true (ArgumentError))`. 

If I try to skip the JRuby argument and just include the JRuby jars with `ruboto gen jruby`, Ruboto proceeds to compile the source files and includes them into the project, but on launch, the built application still asks for the core.apk

Build environment: 
OS: OSX Yosemite
Ruby: 2.2.0
JRuby-Jars: jruby-jars-1.7.18
Ruboto: 1.2.0

**Comment by rscottm** [comment]
Try --target android-19

I think that what it's looking for.

**Comment by donv** [comment]
Hi @awernick !

Did @rscottm 's suggestion help you?

**Comment by danielpassos** [comment]
@awernick Have you tried the @rscottm suggestion?

**Comment by awernick** [comment]
@danielpassos @donv its been a while since I messed around with Ruboto, but I remember that the issue was caused because of something I was missing in my environment. So I believe @rscottm helped me resolve my issue in the end.

**Comment by danielpassos** [comment]
Thanks for the reply @awernick
