### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by webofbits** [ruboto/ruboto#694]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto: 1 year

My experience with HTML, CSS, JavaScript, and Jekyll: 4 year

My experience using git and GitHub: 1 year

My other interests and passions: rails, sinatra, android, linux, qt

**Comment by donv** [comment]
Hi @webofbits !

Welcome to the project!  Glad to have you with us.

Could you start by completing some of the tutorials on the wiki and report how that goes?  Be extra aware of how friendly the tutorials are to newcomers, and report bugs if there are any.

**Comment by webofbits** [comment]
Hi, thanks for accept me on the team,

I need to check all the tutorials and observe if i can improve some of them?


https://github.com/ruboto/ruboto/wiki/Tutorials-and-examples

On 10 February 2015 at 04:59, Uwe Kubosch <notifications@github.com> wrote:

> Hi @webofbits <https://github.com/webofbits> !
>
> Welcome to the project! Glad to have you with us.
>
> Could you start by completing some of the tutorials on the wiki and report
> how that goes? Be extra aware of how friendly the tutorials are to
> newcomers, and report bugs if there are any.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruboto/ruboto/issues/694#issuecomment-73658587>.
>



-- 
      *Cristiano de Araujo *
*      Telegram = '*+55 85 9603 5746'

10101010101.' .`.\._0 0 _.|._ 1 1_./.`. '.0101010101010101010
01010101. ' .' . .\._` ` _|_ ` `_./. . '. ' .0101010101010101
 _1.1- ' . ' .' . .\._` ` | ` `_./. . '. ' . ` -0.0_010101010
`-._. - ` . ' .' . .\._` `|` `_./. . '. ' . ` - ._.-'01010101
    `-._ ` . ' .' . .\._` | `_./. . '. ' . ` _.-'   010101010
        `-._. ' .' . .\._`|`_./. . '. ' ._.-'        01010101
            `-._ .' . .\._|_./. . '. _.-'             0101010
                `-.____.\.|./.____.-'                  010101
                 _/_/__\_\|/_/__\_\_                     1010
________________/.--##/#//-\\#\##--.\_______________________1
               // \##{-(@)=(@)-}##/ \\                      0
              || _.-'.\-\VVV/-/.`-._ ||                  0101
             _|-'_ . -./--|--\.- .- `-|_               101010
         _.-'' -_ . -./.- | -.\.- .- _- `-._          1010101
     _.-',  ' -_ . -./.- `|` -.\.- .- _- `  `-._     10101010
 _.-' . ,  ' -_ . -./.- ` | ` -.\.- .- _- `  , .`-._101010101
'0 - . ,  ' -_ . -./.- ` `|` ` -.\.- .- _- `  , . -1`10101010
010101010'0-_ . -./.- ` ` | ` ` -.\.- .- _-0`0101010101010101
1010101010101. -./.- ` ` -|- ` ` -.\.- .-10101010101010101010
01010101010101-./.-1`1`1-.|.-0`0`0-.\.-0101010101010101010101
10101010101010101010101010|1010101010101010101010101010101010

**Comment by donv** [comment]
That would be great!  Most important is just to complete some of them so you get a feeling of Ruboto development.

**Comment by webofbits** [comment]
You telling me to folow the tutorials to get more experience in ruboto. ok! i ´ll do it at night. i have linux ubuntu 14 installed as main OS. right?

**Comment by donv** [comment]
Ubuntu 14 should do.

**Comment by donv** [comment]
Hi @webofbits !

How are you doing with the tutorials?  Have you tried some of them?

**Comment by danielpassos** [comment]
@webofbits are you interesting in any specific issue?

**Comment by danielpassos** [comment]
Hi,

Since this issue does not has any activity for a long time, I'm closing it. Feel free to reopen it or ping me in the specific issue you have interesting in work on.
