### ISSUE TITLE
The HAXM installer for OS X has changed name

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#703]
```
$ ll ~/android-sdk-macosx/extras/intel/Hardware_Accelerated_Execution_Manager/
total 1064
-rw-r--r--  1 uwe  staff   24048 Mar 13 19:08 HAXM installation
-rw-r--r--  1 uwe  staff  219131 Mar 13 19:08 IntelHAXM_1.1.1_for_10_9_and_above.dmg
-rw-r--r--  1 uwe  staff  265777 Mar 13 19:08 IntelHAXM_1.1.1_for_below_10_9.dmg
-rw-r--r--  1 uwe  staff    4892 Mar 13 19:08 Release Notes.txt
-rw-r--r--  1 uwe  staff    2142 Mar 13 19:08 readme.txt
-rw-r--r--  1 uwe  staff   15876 Mar 13 19:08 silent_install.sh
-rw-r--r--  1 uwe  staff    2549 Mar 13 19:08 source.properties
```
We need to run the right installer during ```ruboto setup```.

**Comment by daneb** [comment]
Will have a look!

**Comment by donv** [comment]
Great!

**Comment by daneb** [comment]
Sorry Uwe, I will try get to this on the weekend.
My Mac power cable broke, and trying to source a supplier! URGH

On Mon, Mar 16, 2015 at 11:48 PM, Uwe Kubosch <notifications@github.com>
wrote:

> Great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruboto/ruboto/issues/703#issuecomment-81956385>.
>



-- 

±± http://www.codedtrue.com ±±

**Comment by donv** [comment]
Hi @daneb !

How are you doing with this?

**Comment by daneb** [comment]
Hi @donv 

I see the code supports IntelHAXM* (which is pretty spot on), but assumes there is only one DMG.
Looks easy enough - set file location based on OS version.

Will submit a patch before Sunday.

**Comment by daneb** [comment]
Opened a branch with proposed solution. 
Will test and let you know

**Comment by donv** [comment]
Great @daneb !  Looking forward to it :smile:

**Comment by danielpassos** [comment]
Hi @daneb Any progress on it? Are you still playing with it?

**Comment by donv** [comment]
@daneb is this covered by your changes?  Can we close it?

**Comment by daneb** [comment]
I believe I've fixed that a while back  - will double check

**Comment by daneb** [comment]
Yip this was fixed and will be resolved with new change with new feature to upgrade HAXM
