### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by sri-sankl** [ruboto/ruboto#704]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto: Ruby: 1.5 years, Java: 1.8 years 

My experience with HTML, CSS, JavaScript, and Jekyll: 3 years

My experience using git and GitHub: 3 years

My other interests and passions:

**Comment by donv** [comment]
Hi @sri-sankl !

Welcome to the project!

As a first step, please install a Ruboto development environment and complete a few of the tutorials.

Please let me know here if you have any questions or suggestions for improvement of the documentation.

**Comment by sri-sankl** [comment]
Thanks for the reply..
I will start installing Ruboto and I will try to impletement some tutorials.

**Comment by donv** [comment]
Hi @sri-sankl !

How are you doing?  Have you tried any of the tutorials?

**Comment by danielpassos** [comment]
Hi @sri-sankl are you interesting in get any specific issue?

**Comment by danielpassos** [comment]
Hi,

Since this issue does not has any activity for a long time, I'm closing it. Feel free to reopen it or ping me in the specific issue you have interesting in work on.
