### ISSUE TITLE
can´t install ruboto

### ISSUE THREAD

**Issue by ghost** [ruboto/ruboto#712]
i am using utopic unicorn and the version of ruby is 2.2.0 and when i try to install seems that are a problem with the path to download. today at nigth i will post the output error message.

**Comment by webofbits** [comment]
ERROR:  Error installing ruboto:
	invalid gem: package metadata is missing in /usr/local/rvm/gems/ruby-2.2.0/cache/rubyzip-1.1.7.gem

**Comment by donv** [comment]
Hi @webofbits !

I'll release Ruboto 1.3.0 later today.  Could you try it and see if it works for you?

**Comment by webofbits** [comment]
gem install ruboto -v '1.3.1'
ERROR:  Could not find a valid gem 'ruboto' (= 1.3.1) in any repository

**Comment by donv** [comment]
gem install ruboto -v 1.3.0

or just

    gem install ruboto

**Comment by webofbits** [comment]
'''root@cristiano:/home/cristiano# rvm use ruby
Using /usr/local/rvm/gems/ruby-2.2.0
root@cristiano:/home/cristiano# gem install ruboto -v 1.3.0
ERROR:  Error installing ruboto:
	invalid gem: package metadata is missing in /usr/local/rvm/gems/ruby-2.2.0/cache/rubyzip-1.1.7.gem
root@cristiano:/home/cristiano# gem install ruboto
ERROR:  Error installing ruboto:
	invalid gem: package metadata is missing in /usr/local/rvm/gems/ruby-2.2.0/cache/rubyzip-1.1.7.gem
root@cristiano:/home/cristiano#

**Comment by webofbits** [comment]
maybe the version of ruby is not compatible with ruboto?

**Comment by webofbits** [comment]
or can be something with my system i think...

**Comment by webofbits** [comment]
i got it using the version 1.9.3 of ruby.

**Comment by danielpassos** [comment]
Hi @webofbits Are you still with this problem? Have you tried using another ruby version?
If you still with this, could you please send the result of?

1. `uname -a`
1. `ruby -v`
1. `gem -v`

**Comment by donv** [comment]
Seems like this is fixed for the original poster. @ghost @webofbits
