### ISSUE TITLE
ruboto setup -y: FATAL -- : undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Zhomart** [ruboto/ruboto#715]
Ruby version: `=> jruby-1.7.19 [ x86_64 ]` by rvm
OSX: `10.10.3`
Ruboto version: `1.3.0`

```
$ ruboto setup -y
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
F, [2015-04-06T00:12:21.280000 #34811] FATAL -- : undefined method `[]' for nil:NilClass (NoMethodError)
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/ruboto-1.3.0/lib/ruboto/util/setup.rb:200:in `check_for_haxm'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/ruboto-1.3.0/lib/ruboto/util/setup.rb:168:in `check_all'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/ruboto-1.3.0/lib/ruboto/util/setup.rb:23:in `setup_ruboto'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/ruboto-1.3.0/lib/ruboto/commands/base.rb:453:in `run'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `run'
org/jruby/RubyKernel.java:1270:in `catch'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/program/class_methods.rb:143:in `run'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/ruboto-1.3.0/lib/ruboto/commands/base.rb:28:in `main'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/ruboto-1.3.0/bin/ruboto:11:in `(root)'
org/jruby/RubyKernel.java:1087:in `load'
/Users/zhomart/.rvm/gems/jruby-1.7.19/bin/ruboto:1:in `(root)'
org/jruby/RubyKernel.java:1107:in `eval'
/Users/zhomart/.rvm/gems/jruby-1.7.19/bin/jruby_executable_hooks:15:in `(root)'
```

**Comment by donv** [comment]
Hi @Zhomart !

Thanks for the report!  I'll take a look as soon as I can.

**Comment by phantomwhale** [comment]
I've put in a PR (above) to fix the issue, although it is likely you will need to still hotpatch haxm from the intel website, I believe, as version 1.1.1, the version the script tries to install from the Android SDK bundle (I think), does not work correctly with Yosemite.

I think downloading and installing the two files here https://software.intel.com/en-us/android/articles/intel-hardware-accelerated-execution-manager-end-user-license-agreement-macosx will get haxm in place for you, and should get `ruboto setup` working correctly.

**Comment by Zhomart** [comment]
Thanks for the efforts. Installed haxm 1.2.1 and got ruboto's latest changes from github, but still getting the same error.

**Comment by daneb** [comment]
Hi Zhomart

Are you running Yosemite?

On Tue, May 19, 2015 at 10:25 PM, Zhomart Mukhamejanov <
notifications@github.com> wrote:

> Thanks for the efforts. Installed haxm 1.2.1 and got ruboto's latest
> changes from github, but still getting the same error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruboto/ruboto/issues/715#issuecomment-103658862>.
>



-- 

±± http://www.codedtrue.com ±±

**Comment by Zhomart** [comment]
@daneb, yes.

OS X `10.10.4 (14E17e)` Yosemite

**Comment by phantomwhale** [comment]
Would you mind pasting the stack trace again?

**Comment by Zhomart** [comment]
When I installed using `git clone`, `gem build` and `gem install` I've got different error. Previously I used different way to install latest changes.

Now I've got same issue as #727 

```
$ ruboto setup -y
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Intel HAXM               : Old   1.1.2/
Android SDK Command adb  : Found
F, [2015-05-19T15:48:20.384000 #33608] FATAL -- : Malformed version number string android-4.4W (ArgumentError)
/Users/zhomart/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/version.rb:206:in `initialize'
/Users/zhomart/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/version.rb:198:in `new'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/util/setup.rb:232:in `check_for_build_tools'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyEnumerable.java:503:in `sort_by'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/util/setup.rb:232:in `check_for_build_tools'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/util/setup.rb:170:in `check_all'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/util/setup.rb:23:in `setup_ruboto'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/commands/base.rb:453:in `run'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `run'
org/jruby/RubyKernel.java:1270:in `catch'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/program/class_methods.rb:143:in `run'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/commands/base.rb:28:in `main'
/Users/zhomart/Development/ruboto/ruboto/bin/ruboto:11:in `(root)'
org/jruby/RubyKernel.java:1087:in `load'
/Users/zhomart/.rvm/gems/jruby-1.7.19/bin/ruboto:1:in `(root)'
org/jruby/RubyKernel.java:1107:in `eval'
/Users/zhomart/.rvm/gems/jruby-1.7.19/bin/jruby_executable_hooks:15:in `(root)'
```

**Comment by phantomwhale** [comment]
Looks like the HAXM version detection is running correctly then; perhaps we could consider this issue resolved, and potentially look into #727 next

**Comment by Zhomart** [comment]
I agree, thank you all for solving this issue. 
In haxm's homepage version `1.1.2` is the latest one. Why does ruboto say 1.1.2 is old? 
```
$ ruboto setup -y
...
Intel HAXM               : Old   1.1.2/
...
```

**Comment by phantomwhale** [comment]
Ah, Ruboto is just doing simple checks here, and assumes that the version it's trying to install (1.1.1) is the latest (which, for the downloaded bundle, it is). 

If the versions don't match, it assumes the other version is an older one. It could equally simply say "Mismatch" there, to be honest. In any case, it shouldn't causes issues with the installation. Just a little confusion.

(I should note, this is all what I have picked up form the script - 16 hours ago, I'd never seen a scrap of Ruboto code in my life, so take all this assumed knowledge with a pinch of salt !)

**Comment by Zhomart** [comment]
One more question, I've cloned the repo and performed bundle install. It changed Gemfile.lock, is it ok?

```
+    ffi (1.9.8-java)
     main (5.3.2)
       arrayfields (>= 4.7.4)
       chronic (>= 0.6.2)
@@ -26,11 +27,19 @@ GEM
       coderay (~> 1.1.0)
       method_source (~> 0.8.1)
       slop (~> 3.4)
+    pry (0.10.1-java)
+      coderay (~> 1.1.0)
+      method_source (~> 0.8.1)
+      slop (~> 3.4)
+      spoon (~> 0.0)
     rake (10.4.2)
     rubyzip (1.1.7)
     slop (3.6.0)
+    spoon (0.0.4)
```

And as I understood to test ruboto I have to run `$ ubuntu_matrix_tests.sh` on OS X. Am I correct?

**Comment by donv** [comment]
Hi @Zhomart !

You can run the Ruboto tests with ```./matrix_tests.sh```.

```./ubuntu_matrix_tests.sh``` runs the same tests, but in a Vagrant Ubuntu virtual machine.  That is way slower, but resembles the Travis CI setup.

The matrix test is pretty wide, so if you want to save some time, you can edit the variables at the top to limit the run.

**Comment by donv** [comment]
Updates to the Gemfile.lock should be OK.

**Comment by Zhomart** [comment]
@donv Thank you.

I will close this issue as it's already solved.

**Comment by donv** [comment]
Thanks!
