### ISSUE TITLE
Webview addJavaScriptInterface

### ISSUE THREAD

**Issue by gfowley** [ruboto/ruboto#719]
Thank you for the latest 1.3.0 release, it's motivated me to return to an unfinished project.
I have run into a problem using Webview I hope I can get some help with...

I am using a Webview and Javascript to provide a custom user interface. The Javascript code needs to get data from the Activity via an object made available to Javascript with Webview.addJavaScriptInterface() :
See [http://developer.android.com/reference/android/webkit/WebView.html#addJavascriptInterface(java.lang.Object, java.lang.String)](http://developer.android.com/reference/android/webkit/WebView.html#addJavascriptInterface(java.lang.Object, java.lang.String))
(Despite the name of this method, the passed object does not require implementation of a Java Interface.)

For testing purposes I am targeting SDK 16 to remove the Java Annotation requirement from the mix.
I can successfully pass existing Java objects and access their methods from a Chrome Javascript console for the Webview:
See https://developer.chrome.com/devtools/docs/remote-debugging#debugging-webviews
... which is very cool btw!

For an instance of java.lang.String (mywebview_activity.rb):
```ruby
@wv.add_javascript_interface java::lang::String.new("abc"), "jsi_string"
```
Javascript console results are as expected:
```
jsi_string.toString()             #=> "abc"
jsi_string.length()               #=> 3
jsi_string.toUpperCase()          #=> "ABC"
```
But for instances of Ruby classes, with various attempts to specify their Java counterparts (mywebview_activity.rb):
```ruby
class JSIRuby
  java_signature "java.lang.String ok()"
  def ok ; "ok" ; end
end

class JSIRubySubJava < java::lang::Object
  java_signature "java.lang.String ok()"
  def ok ; "ok" ; end
end

@wv.add_javascript_interface JSIRuby.new,                   "jsi_ruby"
@wv.add_javascript_interface JSIRubySubJava.new,            "jsi_rubysubjava"
@wv.add_javascript_interface JSIRuby.new.to_java,           "jsi_ruby_to_java"
@wv.add_javascript_interface JSIRubySubJava.new.to_java,    "jsi_rubysubjava_to_java"
```
Some Java Object methods are accessible from Javascript:
```
jsi_ruby.toString()               #=> "#<JSIRuby:0x3fd64234>"
jsi_ruby_tojava.toString()        #=> "#<JSIRuby:0x1af07fd7>"
jsi_rubysubjava.toString()        #=> "org.jruby.proxy.java.lang.Object$Proxy0@e176b18"
jsi_rubysubjava_tojava.toString() #=> "org.jruby.proxy.java.lang.Object$Proxy0@36a420c4"
```
But not the Ruby methods:
```
jsi_ruby.ok()                     #=> Uncaught TypeError: undefined is not a function
jsi_ruby_tojava.ok()              #=> Uncaught TypeError: undefined is not a function
jsi_rubysubjava.ok()              #=> Uncaught TypeError: undefined is not a function
jsi_rubysubjava_tojava.ok()       #=> Uncaught TypeError: undefined is not a function
```
I also tried a Ruby class with explicit Java backing class:
```
ruboto gen subclass java.lang.Object --name=JSIJavaCustom --method_base=none
```
... created Java methods (JSIJavaCustom.java):
```java
public java.lang.String ok() {
  if (ScriptLoader.isCalledFromJRuby()) return "oops! - ScriptLoader.isCalledFromJRuby()";
  if (!JRubyAdapter.isInitialized()) {
    Log.i("Method called before JRuby runtime was initialized: JSIJavaCustom#ok");
    return "oops! - !JRubyAdapter.isInitialized()";
  }
  String rubyClassName = scriptInfo.getRubyClassName();
  if (rubyClassName == null) return "oops! - rubyClassName == null";
  return (java.lang.String) JRubyAdapter.runRubyMethod(java.lang.String.class,  scriptInfo.getRubyInstance(), "ok");
}

public java.lang.String ok_java() {
  return "ok_java";
}
```
... created Ruby methods (jsi_java_custom.rb):
```ruby
class JSIJavaCustom
  java_signature "java.lang.String ok()"
  def ok
    "ok"
  end
end
```
... passed an instance to the Webview (mywebview_activity.rb):
```ruby
require_relative 'jsi_java_custom.rb'
@wv.add_javascript_interface JSIJavaCustom.new,             "jsi_javacustom"
```
For Javascript console result:
```
jsi_javacustom.toString()         #=> "#<JSIJavaCustom:0x33a028c6>"
jsi_javacustom.ok_java()          #=> Uncaught TypeError: undefined is not a function
jsi_javacustom.ok()               #=> Uncaught TypeError: undefined is not a function
```
...it seems that only the Java superclass methods are accessible.

I did all of the above with and without java_signature specified.

A final effort with .become_java! :
See https://github.com/jruby/jruby/wiki/GeneratingJavaClasses
...went nowhere fast:
```ruby
# .newInstance() causes java.lang.InstantiationException: class org.jruby.RubyObject has no zero argument constructor
#  @wv.add_javascript_interface (JSIRuby.become_java!).newInstance(), "jsi_ruby_become_java"

# .become_java! does not work for subclasses of Java classes : https://github.com/jruby/jruby/issues/2359
# @wv.add_javascript_interface (JSIRubySubJava.become_java!).new, "jsi_rubysubjava_become_java"
```
Right now I have no idea what else to try.

Have I missed something about Ruboto/JRuby to Java interfacing ?
Does the Android Webview require a specific Java-ism that Ruboto/JRuby interfacing does not provide ?

Repo is at https://github.com/gfowley/mywebview

Thanks.
-gf-

**Comment by gfowley** [comment]
After some random Googling I found this in the proguard-project.txt file in Ruboto-IRB:
```
# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
# public *;
#}
```
That file is provided by the Android SDK. It seems that [ProGuard](http://proguard.sourceforge.net/) will strip methods from the interface class because they are not referenced by other bytecode.
I changed proguard-project.txt as recommended:
```
-keepclassmembers class net.iqeo.mywebview.JSIRuby {
  public *;
}
-keepclassmembers class net.iqeo.mywebview.JSIRubySubJava {
  public *;
}
-keepclassmembers class net.iqeo.mywebview.JSIJavaCustom {
  public *;
}
```
And also:
```
-keep class net.iqeo.mywebview.JSIRuby {
*;
}
-keep class net.iqeo.mywebview.JSIRubySubJava {
*;
}
-keep class net.iqeo.mywebview.JSIJavaCustom {
*;
}
```
Neither made a difference to the Javascript console results, but since it's the only lead I will dig into this further:
* Review build process to see if ProGuard is actually used.
* Check class and jar files for it's effect.
* Disable ProGuard if possible ?
* 'Protect' these class methods by calling them directly ?

**Comment by gfowley** [comment]
Nope, that wasn't it.

Proguard is not run for debug builds, only for release builds. Even then it's disabled by default in project.properties:
```
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
# proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
```

**Comment by donv** [comment]
Hi @gfowley !

Taking a look now.

**Comment by donv** [comment]
No luck, yet.  I get the same behaviour as you.

**Comment by donv** [comment]
Woohoo!  Some success!  I am able to call a method on a Ruby object implementing a Java interface.

Still not sure why none of the other examples work, but I'll focus on something that works :smile: 

If you add this line on 

```Ruby
    @wv.add_javascript_interface java.lang.Runnable.impl{puts 'run'}, 'jsir'
```
then you can call

```JavaScript
jsir.run()
```

and you will get "run" in your stdout log.

You should be able to create your own interfaces for other methods.  If we could find an interface with a method that takes Object... and returns Object, we could use it for any method call.

**Comment by donv** [comment]
Best alternative for now:

Add ```JsiBridge.java``` to ```src```:

```Java
interface JsiBridge {
    Object ok();
}
```

Attach it to the WebView with:

```Ruby
    @wv.add_javascript_interface Java::JsiBridge.impl{'ok'},    'jsib'
```

Call the method with:

```JavaScript
jsib.ok()
```

Still working on exposing a Ruby class somehow.

**Comment by donv** [comment]
More success!  Got the Ruby class with backing Java class variant working!

Default generated src/net/iqeo/mywebview/JsiJavaCustom.java (notice the slight name change JSI => Jsi):

```Java
// Generated Ruboto subclass with method base "none"

package net.iqeo.mywebview;

import org.ruboto.JRubyAdapter;
import org.ruboto.Log;
import org.ruboto.Script;
import org.ruboto.ScriptInfo;
import org.ruboto.ScriptLoader;

public class JsiJavaCustom extends java.lang.Object implements org.ruboto.RubotoComponent {

  public JsiJavaCustom() {
    super();
  }

  private final ScriptInfo scriptInfo = new ScriptInfo();
  public ScriptInfo getScriptInfo() {
      return scriptInfo;
  }

  /****************************************************************************************
   *
   *  Generated Methods
   */

  public java.lang.String ok() {
    if (ScriptLoader.isCalledFromJRuby()) return "oops! - ScriptLoader.isCalledFromJRuby()";
    if (!JRubyAdapter.isInitialized()) {
      Log.i("Method called before JRuby runtime was initialized: JsiJavaCustom#ok");
      return "oops! - !JRubyAdapter.isInitialized()"; 
    }
    String rubyClassName = scriptInfo.getRubyClassName();
    if (rubyClassName == null) return "oops! - rubyClassName == null";
    return (java.lang.String) JRubyAdapter.runRubyMethod(java.lang.String.class, scriptInfo.getRubyInstance(), "ok");
  }

  {
    scriptInfo.setRubyClassName(getClass().getSimpleName());
    ScriptLoader.loadScript(this);
  }

}
```

Implement Ruby method in ```src/jsi_custom_java```:

```Ruby
class JsiJavaCustom
  def ok
    'ok'
  end
end
```

Import into WebView with:

```Ruby
    @wv.add_javascript_interface Java::NetIqeoMywebview::JsiJavaCustom.new, 'jsi'
```

Use in JavaScript:

```JavaScript
jso.ok()
```

**Comment by donv** [comment]
@gfowley Does this fix this issue for you?

We (or you) could change the value of the ```JsiJavaCustom``` to point to the Java class instead of the Ruby class.  That can be done during class loading and/or instance creation, or as a ```java_import net.iqeo.mywebview.JsiJavaCustom``` call in your source.

**Comment by gfowley** [comment]
Wow! that's great, thanks.

I have an alternative approach using ```WebViewClient#shouldInterceptRequest``` but that has me knee-deep in browser security and Javascript callbacks. Your solution for a Ruby class with Java backing class looks much better to me.

Coincidentally, I ran into a letter case issue with Ruby-ish method names for WebSettings:
```ruby
@wv.settings.allow_file_access_from_file_urls = true  #=> NoMethodError
@wv.settings.allow_file_access_from_file_URLs = true  #=> NoMethodError
@wv.settings.setAllowFileAccesFromFileURLs(true)      #=> Java method name works
```
..but the penny didn't drop about the original problem.

I will give your approach a try this evening.

**Comment by gfowley** [comment]
That works nicely.

I did run into an interesting problem while implementing it in my original application named ```net.iqeo.try_webview``` with activity ```TryWebviewActivity```. My attempts to specify the FQCN:
```ruby
@wc.add_javascript_interface Java::NetIqeoTryWebview::Jsi.new, 'jsi'
```
...resulted in log errors locating the class at ...net.iqeo.try.webview.Jsi, which isn't right. I evaded the issue by copying code into the simpler named ```mywebview``` project.

So, as I see it, the requirements for a Ruby class for use with WebView#addJavascriptInterface are:

* The Ruby class should be backed by a Java class. This may be created by subclassing java.lang.Object with the command:
```
ruboto gen subclass java.lang.Object --name=Myjsi --method_base=none```.
```
* The first letter of the class name should be the only uppercase letter to avoid Ruby/Java name conversion issues, eg; ```Myjsi``` not ```MyJsi``` / ```MyJSI```.
* Avoid underscores in the ```--package``` name when creating the Ruboto project to simplify the CamelCase for the fully qualified class name.
* An instance of the Java class should be passed to WebView#addJavaScriptInterface:
```
webview.add_javascript_interface( Java::CamelCasePackageName::Myjsi.new, "myjsi")  
```
* For methods to be accessible from Javascript, the Java backing class should contain methods that delegate to the Ruby class, eg:
```java
public java.lang.String wifi( int x, int y ) {
  return (java.lang.String) JRubyAdapter.runRubyMethod(java.lang.String.class, scriptInfo.getRubyInstance(), "wifi", new Object[]{ x, y });
}
```
That works for me.

**Comment by gfowley** [comment]
Oops! since you tagged this with 'bug' I shouldn't have closed this on you.

**Comment by gfowley** [comment]
Just to be complete... when targeting android-17 or later the methods of the Java backing class to be accessed from Javascript require the ```@JavacriptInterface``` annotation:

```java

import android.webkit.JavascriptInterface;

public class Jsi extends java.lang.Object implements org.ruboto.RubotoComponent {

...

  @JavascriptInterface
  public java.lang.String wifi( int x, int y ) {
    return (java.lang.String) JRubyAdapter.runRubyMethod(java.lang.String.class, scriptInfo.getRubyInstance(), "wifi", new Object[]{ x, y });
  }

...

```
I verified, this works.

**Comment by donv** [comment]
Thanks @gfowley !

I think I'll change this to ```support``` since we don't actually change anything in Ruboto.

**Comment by donv** [comment]
@gfowley Could I ask you to write a tutorial on using WebView with Ruboto?

**Comment by gfowley** [comment]
Yes, I'd be happy to.

I am experimenting with app control of the webview via ```WebView#evaluateJavascript```. Combined with your resolution of my trouble with ```WebView#addJavascriptInterface``` I will have learned enough to say something useful about bidirectional interfacing between app and webview.

**Comment by donv** [comment]
Great!  Could you open a ticket for it here and mark it with "Documentation" and Milestone 1.3.1 ?
