### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by panasyuk** [ruboto/ruboto#725]

**Comment by donv** [comment]
Hi @panasyuk !

Welcome to the project!

What experience do you have with Android or Java?

What experience do you have with writing documentation?

What experience do you have with Ruby and Ruboto?

Have you tried setting up the Ruboto development environment and complete some of the tutorials?

**Comment by panasyuk** [comment]
Hi! I have no experience both with Java and Android (tried myself in
writing "hello world") and writing docs. But i have over 6 years of
experience developing in Ruby (web applications mainly) and I also tried
Ruboto to automate some things on my Android device. I will look at
tutorials in details in order to pick my Ruboto experience up.

сб, 2 мая 2015, 13:42, Uwe Kubosch <notifications@github.com>:

Hi @panasyuk <https://github.com/panasyuk> !

**Comment by donv** [comment]
Great!  Please let me know when you have completed any tutorial, even just "Hello world!" in Ruboto.

**Comment by danielpassos** [comment]
Hi,

Since this issue does not has any activity for a long time, I'm closing it. Feel free to reopen it or ping me in the specific issue you have interesting in work on.
