### ISSUE TITLE
Any reference to net/https throws LoadError for org/bouncycastle/bcpkix-jdk15on/1.47/bcpkix-jdk15on-1.47

### ISSUE THREAD

**Issue by makuchaku** [ruboto/ruboto#726]
In any ruby script, do 
require "net/https"

Upon running the apk in emulator, following error is seen

I/System.out( 7553): RuntimeError: 
I/System.out( 7553): 	you might need to reinstall the gem which depends on the missing jar
I/System.out( 7553): no such file to load -- org/bouncycastle/bcpkix-jdk15on/1.47/bcpkix-jdk15on-1.47 (LoadError)
I/System.out( 7553):    do_require at /data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/jar_dependencies.rb:202
I/System.out( 7553):   require_jar at /data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/jar_dependencies.rb:151
I/System.out( 7553):   require_jar at /data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/jar_dependencies.rb:211
I/System.out( 7553):        (root) at /data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/jopenssl/load.rb:9
I/System.out( 7553):       require at org/jruby/RubyKernel.java:1071
I/System.out( 7553):        (root) at /data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/openssl.rb:1
I/System.out( 7553):       require at org/jruby/RubyKernel.java:1071
I/System.out( 7553):        (root) at /data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/openssl.rb:1
I/System.out( 7553):       require at org/jruby/RubyKernel.java:1071
I/System.out( 7553):        (root) at /data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/1.9/net/https.rb:1
I/System.out( 7553):       require at org/jruby/RubyKernel.java:1071
I/System.out( 7553):        (root) at /data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/1.9/net/https.rb:22
I/System.out( 7553):       require at org/jruby/RubyKernel.java:1071
I/System.out( 7553):        (root) at /storage/emulated/0/Android/data/com.makulabs.unlimited.memes/files/scripts/app/common/net.rb:1
E/AndroidRuntime( 7553): FATAL EXCEPTION: ScriptLoader for Java::ComMakulabsUnlimitedMemes::MainActivity
E/AndroidRuntime( 7553): Process: com.makulabs.unlimited.memes, PID: 7553
E/AndroidRuntime( 7553): org.jruby.embed.EvalFailedException: (RuntimeError) 
E/AndroidRuntime( 7553): 
E/AndroidRuntime( 7553): 	you might need to reinstall the gem which depends on the missing jar
E/AndroidRuntime( 7553): 
E/AndroidRuntime( 7553): no such file to load -- org/bouncycastle/bcpkix-jdk15on/1.47/bcpkix-jdk15on-1.47 (LoadError)
E/AndroidRuntime( 7553): 	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133)
E/AndroidRuntime( 7553): 	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1340)
E/AndroidRuntime( 7553): 	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1333)
E/AndroidRuntime( 7553): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7553): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 7553): 	at org.ruboto.JRubyAdapter.runScriptlet(JRubyAdapter.java:104)
E/AndroidRuntime( 7553): 	at org.ruboto.ScriptLoader$1.run(ScriptLoader.java:79)
E/AndroidRuntime( 7553): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 7553): Caused by: org.jruby.exceptions.RaiseException: (RuntimeError) 
E/AndroidRuntime( 7553): 
E/AndroidRuntime( 7553): 	you might need to reinstall the gem which depends on the missing jar
E/AndroidRuntime( 7553): 
E/AndroidRuntime( 7553): no such file to load -- org/bouncycastle/bcpkix-jdk15on/1.47/bcpkix-jdk15on-1.47 (LoadError)
E/AndroidRuntime( 7553): 	at RUBY.do_require(/data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/jar_dependencies.rb:202)
E/AndroidRuntime( 7553): 	at RUBY.require_jar(/data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/jar_dependencies.rb:151)
E/AndroidRuntime( 7553): 	at RUBY.require_jar(/data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/jar_dependencies.rb:211)
E/AndroidRuntime( 7553): 	at RUBY.(root)(/data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/jopenssl/load.rb:9)
E/AndroidRuntime( 7553): 	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
E/AndroidRuntime( 7553): 	at RUBY.(root)(/data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/openssl.rb:1)
E/AndroidRuntime( 7553): 	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
E/AndroidRuntime( 7553): 	at RUBY.(root)(/data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/shared/openssl.rb:1)
E/AndroidRuntime( 7553): 	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
E/AndroidRuntime( 7553): 	at RUBY.(root)(/data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/1.9/net/https.rb:1)
E/AndroidRuntime( 7553): 	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
E/AndroidRuntime( 7553): 	at RUBY.(root)(/data/app/org.ruboto.core-1/base.apk!/jruby.home/lib/ruby/1.9/net/https.rb:22)
E/AndroidRuntime( 7553): 	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
E/AndroidRuntime( 7553): 	at RUBY.(root)(/storage/emulated/0/Android/data/com.makulabs.unlimited.memes/files/scripts/app/common/net.rb:1)
W/ActivityManager(  480):   Force finishing activity com.makulabs.unlimited.memes/.MainActivity

Android target
id: 1 or "android-21"
     Name: Android 5.0.1
     Type: Platform
     API level: 21
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.

Emulator : Genymotion
Image : Google Nexus 5, Android 5.0.0 API 21

gem list --local
*** LOCAL GEMS ***
aasm (4.0.5)
actionmailer (4.1.8, 4.1.5, 4.1.2, 3.2.15)
actionpack (4.1.8, 4.1.5, 4.1.2, 3.2.15)
actionview (4.1.8, 4.1.5, 4.1.2)
activemodel (4.1.8, 4.1.2, 3.2.15)
activerecord (4.1.8, 4.1.2, 3.2.15)
activeresource (3.2.15)
activesupport (4.1.8, 4.1.5, 4.1.2, 3.2.15)
addressable (2.3.8, 2.3.7, 2.3.6)
ancestry (2.0.0)
arel (5.0.1.20140414130214, 3.0.2)
arrayfields (4.9.2)
attr_required (1.0.0)
audited (3.0.0)
audited-activerecord (3.0.0)
awesome_print (1.2.0)
bcrypt (3.1.9)
bigdecimal (1.2.4)
bind-it (0.2.7)
binged (1.1.0)
birch (0.0.8)
bouncy-castle-java (1.5.0147)
bson (2.3.0, 1.11.0, 1.9.2)
bson_ext (1.11.0, 1.9.2)
buftok (0.2.0)
builder (3.2.2, 3.0.4)
bundler (1.6.3)
capistrano (3.3.5, 3.2.1)
capistrano-bundler (1.1.3, 1.1.2)
capistrano-rails (1.1.2, 1.1.1)
capistrano-rvm (0.1.2)
capistrano-stats (1.1.1)
chatterbot (0.9.3, 0.9.1, 0.9.0)
chronic (0.10.2)
coderay (1.1.0)
coffee-rails (4.0.1)
coffee-script (2.3.0, 2.2.0)
coffee-script-source (1.8.0, 1.7.0)
colorize (0.7.5, 0.7.4, 0.7.3)
commander (4.1.6)
connection_pool (2.1.0)
dalli (2.7.1)
dancroak-twitter-search (0.5.8)
database_cleaner (1.3.0)
decisiontree (0.4.0)
delayed_job (4.0.4)
delayed_job_mongoid (2.1.0)
devise (3.4.1)
diff-lcs (1.2.5)
docile (1.1.5)
domain_name (0.5.21)
doorkeeper (1.4.0)
easy_diff (0.0.3)
engtagger (0.2.0)
equalizer (0.0.10, 0.0.9)
erubis (2.7.0)
ethon (0.7.3)
execjs (2.2.2, 2.2.1)
factory_girl (4.5.0)
factory_girl_rails (4.5.0)
faraday (0.9.1, 0.9.0)
faraday_middleware (0.9.1)
fastercsv (1.5.5)
fastimage (1.6.3)
fattr (2.2.2)
fb_graph (2.7.17)
ferret (0.11.8.5)
ffi (1.9.8, 1.9.3)
font-awesome-rails (4.2.0.0)
fuzzy-string-match (0.9.6)
geocoder (1.2.6)
geokit (1.9.0)
glebtv_mongoid_userstamp (0.4.1)
googl (0.6.3)
google-search (1.0.3)
google_places (0.27.0)
gsearch-parser (0.3.8)
guess_html_encoding (0.0.9)
haml (4.0.6)
hashie (3.3.2, 3.2.0)
higcm (0.0.5)
highline (1.6.21)
hike (1.2.3)
hirb (0.7.2)
houston (2.0.0)
htmlentities (4.3.3, 4.3.2)
http (0.6.2, 0.5.1)
http-cookie (1.0.2)
http_parser.rb (0.6.0)
httparty (0.13.3, 0.13.1, 0.10.2)
httpclient (2.5.3.3)
i18n (0.6.11, 0.6.9, 0.6.5)
instagram (1.1.3)
io-console (0.4.2)
jbuilder (2.1.1, 1.5.3)
journey (1.0.4)
jquery-datatables-rails (3.1.1)
jquery-rails (3.1.2, 3.1.1)
jquery-ui-rails (5.0.3)
jruby-jars (1.7.20, 1.7.13)
jruby-openssl (0.9.4)
json (1.8.2, 1.8.1)
jwt (1.2.0)
kaminari (0.16.1, 0.14.1)
kronic (1.1.3)
launchy (2.4.3, 2.4.2)
lda-ruby (0.3.8)
levenshtein-ffi (1.1.0)
libv8 (3.16.14.3 x86_64-darwin-13)
linguistics (2.0.3)
liquid (2.5.3)
loggability (0.11.0)
logglier (0.2.11)
mail (2.6.3, 2.6.1, 2.5.4)
main (5.3.2)
map (6.5.4)
mechanize (2.7.3)
memoizable (0.4.2)
method_source (0.8.2)
mime-types (2.4.3, 2.3, 1.25.1, 1.25)
mini_portile (0.6.2, 0.6.0)
minitest (5.4.3, 5.3.5, 4.7.5)
mongo (1.11.0, 1.9.2)
mongoid (4.0.0)
mono_logger (1.1.0)
multi_json (1.10.1, 1.8.2)
multi_xml (0.5.5)
multipart-post (2.0.0)
narray (0.6.0.9)
naught (1.0.0)
net-http-digest_auth (1.4)
net-http-persistent (2.9.4)
net-scp (1.2.1)
net-ssh (2.9.1)
netrc (0.7.7)
nickel (0.1.6)
nokogiri (1.6.6.2, 1.6.3.1, 1.5.11)
ntlm-http (0.1.1)
oauth (0.4.7)
optionable (0.2.0)
origin (2.1.1)
orm_adapter (0.5.0)
parse-ruby-client (0.3.0)
plucky (0.6.6)
polyglot (0.3.5, 0.3.3)
polylines (0.2.0)
progressbar (0.21.0)
pry (0.10.0)
psych (2.0.5)
punkt-segmenter (0.9.1)
rack (1.5.2, 1.4.5)
rack-cache (1.2)
rack-oauth2 (1.0.8)
rack-test (0.6.2)
rails (4.1.8, 4.1.2)
railties (4.1.8, 4.1.2)
rake (10.4.2, 10.3.2, 10.1.0)
ralert (0.3.1)
rb-libsvm (1.1.5)
rbtagger (0.4.7)
rdoc (4.1.0)
responders (1.1.2)
rest-client (1.7.2)
rjb (1.4.9)
ruboto (1.3.0, 1.1.1)
ruby-fann (1.2.6)
ruby-progressbar (1.7.5)
ruby-readability (0.7.0)
ruby-stemmer (0.9.3)
ruby-web-search (0.0.2)
ruby_events (1.1.0)
RubyInline (3.12.3)
rubyzip (1.1.6, 0.9.9)
rvm (1.11.3.9)
rwordnet (0.1.3)
sass (3.2.19)
sass-rails (4.0.5)
scalpel (0.2.1)
schiphol (1.0.1)
sentimental (1.0.3)
shoulda (3.5.0)
shoulda-context (1.2.1)
shoulda-matchers (2.7.0)
simple_oauth (0.2.0)
slop (3.5.0)
sprockets (2.12.3, 2.12.1, 2.2.2)
sprockets-rails (2.2.2, 2.1.3)
srx-english (0.1.2)
sshkit (1.6.1, 1.5.1)
stanford-core-nlp (0.5.1)
tactful_tokenizer (0.0.5)
term-ansicolor (1.0.7)
terminal-table (1.4.5)
test-unit (2.1.2.0)
tf-idf-similarity (0.1.3)
thor (0.19.1)
thread_safe (0.3.5, 0.3.4)
tilt (1.4.1)
treat (2.1.0)
treetop (1.4.15)
tumblr_client (0.8.5)
twitter (5.11.0, 5.8.0)
typhoeus (0.7.1, 0.3.3)
tzinfo (1.2.2, 1.2.1, 0.3.38)
uea-stemmer (0.10.1)
unf (0.1.4)
unf_ext (0.0.6)
unicode_utils (1.4.0)
warden (1.2.3)
webrobots (0.1.1)
whatlanguage (1.0.5)
wombat (2.2.1)
yomu (0.2.0)
ZenTest (4.10.1)
zip (2.0.2)

**Comment by gfowley** [comment]
JRuby OpenSSL dependency version compatibility can be picky.

Please try latest versions of ```jruby-jars``` 1.x (1.7.21), ```jruby-openssl``` (0.9.8), and ```bouncy-castle-java``` (1.5.0147). 

I see a couple of ```jruby-jars`` versions in the gem list, make sure the latest version is installed in the project```libs``` directory.

**Comment by donv** [comment]
@makuchaku @gfowley Any progress on this issue?

**Comment by gfowley** [comment]
@makuchaku : Is this still a current issue for you ?

**Comment by donv** [comment]
@makuchaku @gfowley I am looking at this now, and it looks like a genuine Ruboto bug :smile: 

The SSL tests have not been run for a while.  Activating them now.

**Comment by qbasicer** [comment]
@gfowley, 

> Please try latest versions of jruby-jars 1.x (1.7.21), jruby-openssl (0.9.8), and bouncy-castle-java (1.5.0147).

Do you have any information on how to do this?  Or is that a separate issue I should raise?
