### ISSUE TITLE
(ArgumentError) unable to create proxy class for class java.util.HashMap : null

### ISSUE THREAD

**Issue by javalovercn** [ruboto/ruboto#729]
--------------------------source code------------------------------
final File currFile = new File(".");
final ClassLoader projClassLoader = ResourceUtil.buildProjClassLoader(currFile);
HCJRubyEngine hcje = new HCJRubyEngine(currFile.getAbsolutePath(), projClassLoader);
try{
	Class c = projClassLoader.loadClass("java.util.HashMap");
	System.out.println("found " + c);//--------print right, see follow result---------
}catch (Exception e) {
	e.printStackTrace();
}
RubyExector.run("p=64.0\n" +
	"q = Math.sqrt p\n" +
	"puts \"square root of #{p} is #{q}\"\n", null, hcje);//---------print right, see following result---------

String androidScript = "require 'java'\n" +
	"java_import 'java.util.HashMap'\n" +
	"class MyHashMap < HashMap\n" +
	"end\n" +
	"return MyHashMap.new\n";
Object out = RubyExector.run(androidScript, null, hcje);
System.out.println("androidScript : " + out + ", and is HashMap : " + (out instanceof HashMap));//---------fail on error---------

-----------------------------enviroment-----------------------------------
RubotoCore-release-1.0.3.apk is loaded by DexClassLoader in Android 4.4.2
-----------------------------run result--------------------------------------
05-25 09:38:00.365: I/System.out(1396): found class java.util.HashMap
05-25 09:38:00.735: I/dalvikvm(1396): Could not find method sun.misc.Unsafe.copyMemory, referenced from method org.jruby.RubyEncoding.encodeUTF16
05-25 09:38:00.735: W/dalvikvm(1396): VFY: unable to resolve virtual method 57752: Lsun/misc/Unsafe;.copyMemory (Ljava/lang/Object;JLjava/lang/Object;JJ)V
....
05-25 09:38:31.895: I/dalvikvm(1396): Jit: resizing JitTable from 4096 to 8192
...
05-25 09:38:34.585: I/System.out(1396): square root of 64.0 is 8.0
05-25 09:38:35.055: W/System.err(1396): java.lang.reflect.InvocationTargetException
05-25 09:38:35.105: W/System.err(1396): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-25 09:38:35.105: W/System.err(1396): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-25 09:38:35.115: W/System.err(1396): 	at org.jruby.javasupport.proxy.JavaProxyClassFactory.invokeDefineClass(JavaProxyClassFactory.java:247)
05-25 09:38:35.645: D/dalvikvm(1396): GC_FOR_ALLOC freed 1727K, 12% free 13424K/15220K, paused 529ms, total 533ms
05-25 09:38:35.665: W/System.err(1396): 	at org.jruby.javasupport.proxy.JavaProxyClassFactory.generate(JavaProxyClassFactory.java:207)
05-25 09:38:35.665: W/System.err(1396): 	at org.jruby.javasupport.proxy.JavaProxyClassFactory.newProxyClass(JavaProxyClassFactory.java:179)
05-25 09:38:35.665: W/System.err(1396): 	at org.jruby.javasupport.proxy.JavaProxyClass.getProxyClass(JavaProxyClass.java:122)
05-25 09:38:35.665: W/System.err(1396): 	at org.jruby.javasupport.proxy.JavaProxyClass.get_with_class(JavaProxyClass.java:693)
05-25 09:38:35.665: W/System.err(1396): 	at org.jruby.javasupport.Java$5.call(Java.java:776)
05-25 09:38:35.665: W/System.err(1396): 	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:661)
05-25 09:38:35.685: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)
05-25 09:38:35.685: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)
05-25 09:38:35.685: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:149)
05-25 09:38:35.685: W/System.err(1396): 	at org.jruby.java.proxies.ConcreteJavaProxy$2.call(ConcreteJavaProxy.java:48)
05-25 09:38:35.735: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)
05-25 09:38:35.735: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)
05-25 09:38:35.745: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:149)
05-25 09:38:35.745: W/System.err(1396): 	at org.jruby.RubyClass.newInstance(RubyClass.java:849)
05-25 09:38:35.745: W/System.err(1396): 	at org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)
05-25 09:38:35.745: W/System.err(1396): 	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrNBlock.call(JavaMethod.java:280)
05-25 09:38:35.745: W/System.err(1396): 	at org.jruby.java.proxies.ConcreteJavaProxy$3.call(ConcreteJavaProxy.java:141)
05-25 09:38:35.785: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306)
05-25 09:38:35.785: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136)
05-25 09:38:35.795: W/System.err(1396): 	at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)
05-25 09:38:35.795: W/System.err(1396): 	at org.jruby.ast.ReturnNode.interpret(ReturnNode.java:92)
05-25 09:38:35.795: W/System.err(1396): 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
05-25 09:38:35.795: W/System.err(1396): 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
05-25 09:38:35.795: W/System.err(1396): 	at org.jruby.ast.RootNode.interpret(RootNode.java:129)
05-25 09:38:35.795: W/System.err(1396): 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_ROOT(ASTInterpreter.java:121)
05-25 09:38:35.795: W/System.err(1396): 	at org.jruby.Ruby.runInterpreter(Ruby.java:893)
05-25 09:38:35.795: W/System.err(1396): 	at org.jruby.Ruby.runInterpreter(Ruby.java:901)
05-25 09:38:35.795: W/System.err(1396): 	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:121)
05-25 09:38:35.845: W/System.err(1396): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-25 09:38:35.845: W/System.err(1396): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-25 09:38:35.855: W/System.err(1396): 	at hc.util.ClassUtil.invoke(ClassUtil.java:61)
05-25 09:38:35.855: W/System.err(1396): 	at hc.server.ui.design.engine.HCJRubyEngine.runScriptlet(HCJRubyEngine.java:72)
05-25 09:38:35.855: W/System.err(1396): 	at hc.server.ui.design.hpj.RubyExector.runNoWait(RubyExector.java:114)
05-25 09:38:35.875: W/System.err(1396): 	at com.homecenter.mobi.ServerMainActivity.onCreate(ServerMainActivity.java:207)
05-25 09:38:35.895: W/System.err(1396): 	at android.app.Activity.performCreate(Activity.java:5231)
05-25 09:38:35.895: W/System.err(1396): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
05-25 09:38:35.915: W/System.err(1396): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
05-25 09:38:35.915: W/System.err(1396): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
05-25 09:38:35.925: W/System.err(1396): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
05-25 09:38:35.925: W/System.err(1396): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
05-25 09:38:35.925: W/System.err(1396): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-25 09:38:35.925: W/System.err(1396): 	at android.os.Looper.loop(Looper.java:136)
05-25 09:38:35.925: W/System.err(1396): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
05-25 09:38:35.945: W/System.err(1396): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-25 09:38:35.965: W/System.err(1396): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-25 09:38:35.965: W/System.err(1396): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
05-25 09:38:35.975: W/System.err(1396): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
05-25 09:38:35.975: W/System.err(1396): 	at dalvik.system.NativeStart.main(Native Method)
05-25 09:38:35.975: W/System.err(1396): Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
05-25 09:38:35.995: W/System.err(1396): 	at java.lang.ClassLoader.defineClass(ClassLoader.java:288)
05-25 09:38:36.015: W/System.err(1396): 	... 51 more
05-25 09:38:36.055: W/System.err(1396): java.lang.reflect.InvocationTargetException
05-25 09:38:36.055: W/System.err(1396): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-25 09:38:36.065: W/System.err(1396): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-25 09:38:36.065: W/System.err(1396): 	at hc.util.ClassUtil.invoke(ClassUtil.java:61)
05-25 09:38:36.065: W/System.err(1396): 	at hc.server.ui.design.engine.HCJRubyEngine.runScriptlet(HCJRubyEngine.java:72)
05-25 09:38:36.065: W/System.err(1396): 	at hc.server.ui.design.hpj.RubyExector.runNoWait(RubyExector.java:114)
05-25 09:38:36.065: W/System.err(1396): 	at com.homecenter.mobi.ServerMainActivity.onCreate(ServerMainActivity.java:207)
05-25 09:38:36.065: W/System.err(1396): 	at android.app.Activity.performCreate(Activity.java:5231)
05-25 09:38:36.085: W/System.err(1396): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
05-25 09:38:36.085: W/System.err(1396): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
05-25 09:38:36.105: W/System.err(1396): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
05-25 09:38:36.105: W/System.err(1396): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
05-25 09:38:36.105: W/System.err(1396): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
05-25 09:38:36.105: W/System.err(1396): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-25 09:38:36.115: W/System.err(1396): 	at android.os.Looper.loop(Looper.java:136)
05-25 09:38:36.115: W/System.err(1396): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
05-25 09:38:36.115: W/System.err(1396): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-25 09:38:36.115: W/System.err(1396): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-25 09:38:36.145: W/System.err(1396): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
05-25 09:38:36.155: W/System.err(1396): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
05-25 09:38:36.155: W/System.err(1396): 	at dalvik.system.NativeStart.main(Native Method)
05-25 09:38:36.165: W/System.err(1396): Caused by: org.jruby.embed.EvalFailedException: (ArgumentError) unable to create proxy class for class java.util.HashMap : null
05-25 09:38:36.165: W/System.err(1396): 	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133)
05-25 09:38:36.165: W/System.err(1396): 	... 20 more
05-25 09:38:36.175: W/System.err(1396): Caused by: org.jruby.exceptions.RaiseException: (ArgumentError) unable to create proxy class for class java.util.HashMap : null
05-25 09:38:36.175: W/System.err(1396): 	at org.jruby.javasupport.proxy.JavaProxyClass.get_with_class(org/jruby/javasupport/proxy/JavaProxyClass.java:695)
05-25 09:38:36.175: W/System.err(1396): 	at RUBY.(root)(<script>:5)
05-25 09:38:36.175: W/System.err(1396): Caused by: java.lang.InternalError
05-25 09:38:36.195: W/System.err(1396): 	at org.jruby.javasupport.proxy.JavaProxyClassFactory.generate(JavaProxyClassFactory.java:215)
05-25 09:38:36.195: W/System.err(1396): 	at org.jruby.javasupport.proxy.JavaProxyClassFactory.newProxyClass(JavaProxyClassFactory.java:179)
05-25 09:38:36.195: W/System.err(1396): 	at org.jruby.javasupport.proxy.JavaProxyClass.getProxyClass(JavaProxyClass.java:122)
05-25 09:38:36.215: W/System.err(1396): 	at org.jruby.javasupport.proxy.JavaProxyClass.get_with_class(JavaProxyClass.java:693)
05-25 09:38:36.225: W/System.err(1396): 	at org.jruby.javasupport.Java$5.call(Java.java:776)
05-25 09:38:36.235: W/System.err(1396): 	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:661)
05-25 09:38:36.235: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)
05-25 09:38:36.245: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)
05-25 09:38:36.245: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:149)
05-25 09:38:36.245: W/System.err(1396): 	at org.jruby.java.proxies.ConcreteJavaProxy$2.call(ConcreteJavaProxy.java:48)
05-25 09:38:36.255: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)
05-25 09:38:36.255: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)
05-25 09:38:36.265: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:149)
05-25 09:38:36.295: W/System.err(1396): 	at org.jruby.RubyClass.newInstance(RubyClass.java:849)
05-25 09:38:36.295: W/System.err(1396): 	at org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)
05-25 09:38:36.315: W/System.err(1396): 	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrNBlock.call(JavaMethod.java:280)
05-25 09:38:36.315: W/System.err(1396): 	at org.jruby.java.proxies.ConcreteJavaProxy$3.call(ConcreteJavaProxy.java:141)
05-25 09:38:36.325: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306)
05-25 09:38:36.325: W/System.err(1396): 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136)
05-25 09:38:36.325: W/System.err(1396): 	at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)
05-25 09:38:36.325: W/System.err(1396): 	at org.jruby.ast.ReturnNode.interpret(ReturnNode.java:92)
05-25 09:38:36.325: W/System.err(1396): 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
05-25 09:38:36.325: W/System.err(1396): 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
05-25 09:38:36.325: W/System.err(1396): 	at org.jruby.ast.RootNode.interpret(RootNode.java:129)
05-25 09:38:36.325: W/System.err(1396): 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_ROOT(ASTInterpreter.java:121)
05-25 09:38:36.325: W/System.err(1396): 	at org.jruby.Ruby.runInterpreter(Ruby.java:893)
05-25 09:38:36.325: W/System.err(1396): 	at org.jruby.Ruby.runInterpreter(Ruby.java:901)
05-25 09:38:36.325: W/System.err(1396): 	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:121)
05-25 09:38:36.325: W/System.err(1396): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-25 09:38:36.355: W/System.err(1396): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-25 09:38:36.355: W/System.err(1396): 	at hc.util.ClassUtil.invoke(ClassUtil.java:61)
05-25 09:38:36.355: W/System.err(1396): 	at hc.server.ui.design.engine.HCJRubyEngine.runScriptlet(HCJRubyEngine.java:72)
05-25 09:38:36.355: W/System.err(1396): 	at hc.server.ui.design.hpj.RubyExector.runNoWait(RubyExector.java:114)
05-25 09:38:36.355: W/System.err(1396): 	at com.homecenter.mobi.ServerMainActivity.onCreate(ServerMainActivity.java:207)
05-25 09:38:36.355: W/System.err(1396): 	at android.app.Activity.performCreate(Activity.java:5231)
05-25 09:38:36.355: W/System.err(1396): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
05-25 09:38:36.385: W/System.err(1396): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
05-25 09:38:36.395: W/System.err(1396): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
05-25 09:38:36.395: W/System.err(1396): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
05-25 09:38:36.395: W/System.err(1396): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
05-25 09:38:36.395: W/System.err(1396): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-25 09:38:36.405: W/System.err(1396): 	at android.os.Looper.loop(Looper.java:136)
05-25 09:38:36.405: W/System.err(1396): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
05-25 09:38:36.405: W/System.err(1396): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-25 09:38:36.415: W/System.err(1396): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-25 09:38:36.415: W/System.err(1396): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
05-25 09:38:36.425: W/System.err(1396): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
05-25 09:38:36.435: W/System.err(1396): 	at dalvik.system.NativeStart.main(Native Method)
05-25 09:38:36.435: W/System.err(1396): Caused by: java.lang.NullPointerException
05-25 09:38:36.455: W/System.err(1396): 	at org.jruby.javasupport.proxy.JavaProxyClassFactory.generate(JavaProxyClassFactory.java:211)
05-25 09:38:36.455: W/System.err(1396): 	... 47 more
05-25 09:38:36.475: W/System.err(1396): java.lang.reflect.InvocationTargetException
05-25 09:38:36.475: W/System.err(1396): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-25 09:38:36.475: W/System.err(1396): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-25 09:38:36.485: W/System.err(1396): 	at hc.util.ClassUtil.invoke(ClassUtil.java:61)
05-25 09:38:36.485: W/System.err(1396): 	at hc.server.ui.design.engine.HCJRubyEngine.runScriptlet(HCJRubyEngine.java:74)
05-25 09:38:36.485: W/System.err(1396): 	at hc.server.ui.design.hpj.RubyExector.runNoWait(RubyExector.java:114)
05-25 09:38:36.485: W/System.err(1396): 	at com.homecenter.mobi.ServerMainActivity.onCreate(ServerMainActivity.java:207)
05-25 09:38:36.485: W/System.err(1396): 	at android.app.Activity.performCreate(Activity.java:5231)
05-25 09:38:36.485: W/System.err(1396): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
05-25 09:38:36.485: W/System.err(1396): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
05-25 09:38:36.485: W/System.err(1396): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
05-25 09:38:36.485: W/System.err(1396): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
05-25 09:38:36.485: W/System.err(1396): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
05-25 09:38:36.485: W/System.err(1396): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-25 09:38:36.515: W/System.err(1396): 	at android.os.Looper.loop(Looper.java:136)
05-25 09:38:36.515: W/System.err(1396): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
05-25 09:38:36.535: W/System.err(1396): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-25 09:38:36.535: W/System.err(1396): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-25 09:38:36.535: W/System.err(1396): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
05-25 09:38:36.535: W/System.err(1396): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
05-25 09:38:36.535: W/System.err(1396): 	at dalvik.system.NativeStart.main(Native Method)
05-25 09:38:36.535: W/System.err(1396): Caused by: java.lang.NullPointerException
05-25 09:38:36.565: W/System.err(1396): 	at org.jruby.javasupport.JavaEmbedUtils.rubyToJava(JavaEmbedUtils.java:282)
05-25 09:38:36.565: W/System.err(1396): 	... 20 more
05-25 09:38:36.575: I/System.out(1396): androidScript : null, and is JLable : false

**Comment by donv** [comment]
Hi @javalovercn !

Thanks for the report.

This may be ```Unsafe.copyMemory``` missing from Android.

**Comment by donv** [comment]
Looking at the source here:  https://android.googlesource.com/platform/libcore/+/9edf43dfcc35c761d97eb9156ac4254152ddbc55/libdvm/src/main/java/sun/misc/Unsafe.java

Unsafe#copyMemory is indeed not implemented.

**Comment by javalovercn** [comment]
Hello,
very glad to receive your replay!

Unsafe.copyMemory is raised before first script result:
----------------------------------
05-25 09:38:34.585: I/System.out(1396): square root of 64.0 is 8.0
----------------------------------
it seem that Ruby script is works right after error of Unsafe.copyMemory.
although sun.misc.Unsafe is based on Sun/Oracle JVM, but the script can also works on Android.

the second script is simple for Ruby ,
---------------begin-------------------
require 'java'
java_import 'java.util.HashMap'
class MyHashMap < HashMap
end
return MyHashMap.new
----------------- end ------------------
I think it maybe caused by classloader, but the code above seems that the classloader can find HashMap rightly. I just want to define a class by Ruby to extend a base class. I am not familiar with JRuby, maybe it is not writed like this in Ruboto. but it raises "(ArgumentError) unable to create proxy class for class java.util.HashMap : null"

help!!!

**Comment by javalovercn** [comment]
-------source in---new HCJRubyEngine(currFile.getAbsolutePath(), projClassLoader)------------------

		
		Class classLocalContextScope = projClassLoader.loadClass("org.jruby.embed.LocalContextScope");
		Class classLocalVariableBehavior = projClassLoader.loadClass("org.jruby.embed.LocalVariableBehavior");
		classScriptingContainer = projClassLoader.loadClass("org.jruby.embed.ScriptingContainer");
		Class[] construParaTypes = {classLocalContextScope, classLocalVariableBehavior, boolean.class};
		Constructor constr = classScriptingContainer.getConstructor(construParaTypes);
		Object[] constrPara = {
				ClassUtil.getField(classLocalContextScope, classLocalContextScope, "THREADSAFE", false),
				ClassUtil.getField(classLocalVariableBehavior, classLocalVariableBehavior, "PERSISTENT", false),
				Boolean.TRUE};
		container = constr.newInstance(constrPara);
		
		if(absPath != null && absPath.length() > 0){
			ArrayList<String> loadPaths = new ArrayList<String>(1);
			loadPaths.add(absPath);
			Class[] paraTypes = {List.class};
			Object[] para = {loadPaths};
			ClassUtil.invoke(classScriptingContainer, container, "setLoadPaths", paraTypes, para, false);
		}
		
		{
			Class[] paraType = {String.class};
			Object[] para = {absPath};
			ClassUtil.invoke(classScriptingContainer, container, "setCurrentDirectory", paraType, para, false);//----------writable directory---------------
		}
		
		{
			Class[] paraType = {Writer.class};
			Object[] para = {errorWriter};
			ClassUtil.invoke(classScriptingContainer, container, "setError", paraType, para, false);
		}
		
		Class[] paraType = {ClassLoader.class};
		Object[] para = {projClassLoader};
		ClassUtil.invoke(classScriptingContainer, container, "setClassLoader", paraType, para, false);
		}catch (Throwable e) {
			e.printStackTrace();
		}
-------------------end--------------------------

**Comment by javalovercn** [comment]
after google, get a url http://www.java2s.com/Open-Source/Android_Free_Code/App/screen/org_rubotoJRubyAdapter_java.htm
find method setUpJRuby, add following code:
--------------------------------------------------------------
            System.setProperty("jruby.compile.mode", "OFF"); // OFF OFFIR JITIR? FORCE FORCEIR
            // System.setProperty("jruby.compile.backend", "DALVIK");
            System.setProperty("jruby.bytecode.version", "1.6");
            System.setProperty("jruby.interfaces.useProxy", "true");
            System.setProperty("jruby.management.enabled", "false");
            System.setProperty("jruby.objectspace.enabled", "false");
            System.setProperty("jruby.thread.pooling", "true");
            System.setProperty("jruby.native.enabled", "false");
            // System.setProperty("jruby.compat.version", "RUBY1_8"); // RUBY1_9 is the default in JRuby 1.7
            System.setProperty("jruby.ir.passes", "LocalOptimizationPass,DeadCodeElimination");
            System.setProperty("jruby.backtrace.style", "normal"); // normal raw full mri

            // Uncomment these to debug/profile Ruby source loading
            // System.setProperty("jruby.debug.loadService", "true");
            // System.setProperty("jruby.debug.loadService.timing", "true");

            // Used to enable JRuby to generate proxy classes
            System.setProperty("jruby.ji.proxyClassFactory", "org.ruboto.DalvikProxyClassFactory");
            System.setProperty("jruby.class.cache.path", appContext.getDir("dex", 0).getAbsolutePath());
--------------------------------------------------------------
now, all scripts works well.
