### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by mindaslab** [ruboto/ruboto#730]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto: Just looking at Ruboto and Android now. Have extensive Ruby and Java experience.

My experience with HTML, CSS, JavaScript, and Jekyll: Thats cool, I am we developer, did some sample blogs in jekyll 

My experience using git and GitHub: Love it really good.

My other interests and passions: Want to make this project better than Rubymotion (lets see)

**Comment by donv** [comment]
Hi @mindaslab !

Welcome to the project!

To get you started, you should look at the tutorials and set up your development environment.

Report back when you have completed a few tutorials or if you get stuck.

**Comment by kinsomicrote** [comment]
Just saw this....i bet I'll follow this path

**Comment by donv** [comment]
@kinsomicrote please do!  :)

**Comment by danielpassos** [comment]
@kinsomicrote Do you have interesting in some specific issue? Can we close this issue?

**Comment by kinsomicrote** [comment]
Yea, you can.
