### ISSUE TITLE
Quick Start Example

### ISSUE THREAD

**Issue by KCErb** [ruboto/ruboto#731]
Hi all,

I'm trying to dust off ruboto and get it running again. There may be a problem with my setup (still looking at that) but this seems unrelated.

When I run
```
ruboto gen app --package org.ruboto.example.quick_start
```

from [here](https://github.com/ruboto/ruboto/wiki/Creating-Your-First-Ruboto-Application#generate-it)
then I get this:

```
KC:apps$ ruboto gen app --package org.ruboto.example.quick_start
WARN: Unresolved specs during Gem::Specification.reset:
      rake (~> 10.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

Generating Android app QuickStart in /Users/KC/Programming/hello-ruboto/tutorials/apps/quick_start...
Error: Target id is not valid. Use 'android list targets' to get the target ids.
```

so it seems something in the quick_start sample is specifying a bad target id . . . not sure what that means.

**Comment by donv** [comment]
Hi @KCErb !

You should verify your development environment using

    ruboto setup -y

It should install the android-16 platform which is the default target.

The default target has moved during the lifetime of the Ruboto project from 8 to 10 to 15, and finally to 16.

**Comment by KCErb** [comment]
Unfortunately that step is also not working for me :grimacing: I posted a comment about the problem on a recently closed pull request: https://github.com/ruboto/ruboto/pull/728#issuecomment-108693493

The `-y` option didn't affect my results.

I should note that my emulator *does* work. When I run `emulator -avd <name>` I get a snappy responsive emulator running so I know that my HAXM / hotfix from before are still functioning as expected.

**Comment by KCErb** [comment]
OK, with my `ruboto setup` working now, I was able to generate the quick_start example, but when I tried to run it I got

```
BUILD FAILED
/Users/KC/android-sdk-macosx/tools/ant/build.xml:483: The SDK Build Tools revision (19.0.1) is too low for project 'QuickStart'. Minimum required is 19.1.0
```

So I went into the sdk manager and got 19.1 and that solved the issue, but it seems that `ruboto setup` is supposed to catch this. It also seems that `ruboto setup` thinks having sdk 16 is sufficient, so I'm not sure why `QuickStart` is asking for a higher SDK Build Tools version . . . any insights? 

I never specified that I was targeting 19.1 or 19.0.1 for that matter, I just used the default:

    $ ruboto gen app --package org.ruboto.example.quick_start

**Comment by danielpassos** [comment]
Hi @KCErb 

1. What command you use to got it? 
1. What ruboto version are you using?

I ran `ant clean release` and it works like a charm

**Comment by KCErb** [comment]
Yup this is resolved, sorry to leave this hanging.

**Comment by danielpassos** [comment]
You don't need to apologize. Thanks for reply!

**Comment by donv** [comment]
Hi @danielpassos !

Please assign this issue to yourself since you did the follow up.  I'd like all closed issues to have an assignee before release docs are created.

Good work!
