### ISSUE TITLE
New release manager

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#732]
Hi @ruboto/team-ruboto !

I have to reduce the time I spend on Ruboto, and there has been an increase in contributors lately, so I'd like to ask if any of you can step up and take some of the tasks from me.

I'll continue to use Ruboto and contribute a lot, but I will not be able to do regular releases and follow up new issues in the tracker.  So basically we need a new project lead who can do the releases and follow up on new issues.

Anybody up for it?

**Comment by KCErb** [comment]
I wish I could! I'm still too green in Ruby (never been involved much with releasing gems for example) and I definitely don't know enough Java to maintain. 

I'll at least say: I'm very grateful for all that you've done @donv! This project seems like a great undertaking and it's a very exciting idea (at least to *this* new programmer) that I can get into app development with Ruby. I hope someone can step-up and pitch in because I'd hate to see this one go fallow.

**Comment by donv** [comment]
I will of course help anyone getting started with releasing the gem.  It is actually incredibly easy :)

We will still share the work of doing code changes.  I just need help with doing the actual release of the gem.  The code base should be releasable on master at any time, so the task is just to decide to do the release and run the task.

The other bit is to respond to new issues by acknowledging that they are received and that they will be considered.

**Comment by daneb** [comment]
Some suggestions and questions, and perhaps the wrong platform but bear with me:
Uwe - does that mean all issues just needing to be acknowledged or resolved?

Secondly - maybe having on the website a vision for Ruboto 2016? That may enable more contributors to come on board and get excited!

Thirdly, I see you continuously replying to new people wanting to assist...can we maybe have a how to with your standard answer? I can put that together by past issues.

Can we maybe do a code pairing session where you walk through some internals of Rubuto?

Lastly - that idea you had of Rubuto on Wikipedia would be awesome. Also if we wrote some tutorials and posted them on popular tutorial sites. That said, I don't know in MY MIND if Ruboto (content of site, tutorials etc) and the technology is "easy" enough to use? We have Rubymotion, Xanarim, ReactNative etc so the market is saturated and ease of use is first prize even if it's only one platform (Android).

I know you have a ton on your plate - but I can help.
I would like to assist with the release management.

**Comment by donv** [comment]
Hi @daneb !

Great that you can help :)  I am very grateful.

The most important thing about the issues is that the reporter gets a response, and that the severity/category of the report is assessed, and the appropriate milestone and tags are attached.  The actual solving of the issue must be a group activity as before where we all chip in where we can.

I agree that publishing a vision for Ruboto 2016 is a good idea.  The vision/plan for Ruboto now resides in the issue tracker in the "milestones":  https://github.com/ruboto/ruboto/milestones .  Each issue is organized in a milestone, and each milestone should have a description of what the main purpose of the release is.

I have been thinking of the "Ruboto developers school" with a step-by-step help for new contributors.  It can be put together from my earlier responses, and I would love to see that happen.

I would love a code pairing session, or even lots of them where we can walk through the code, and (more importantly) I can share all the history and thoughts that lie behind the code.  Very little can be captured in code comments :)

Having a Ruboto Wikipedia page would be great.  I hope someone can make it happen.

Posting tutorials, blogs, new feature snippets, videos with how-tos would all attract more developers and make it easier for new developers and contributors to join the project.  I would love to see that happen, and I can assist anyone wanting to explore this.

I welcome all help in the Ruboto project, and I appreciate very much that you can help with the release management.  I have postponed the next release, 1.3.1, to july.  Let's do that one together, and go from there.

The existing release process is documented here:  https://github.com/ruboto/ruboto/wiki/Release-process

**Comment by daneb** [comment]
Hi @donv 

Sounds a plan - I'm in.

**Comment by kinsomicrote** [comment]
I would very much love to be involved with Ruboto but I'm on my way to being a junior ruby developer. Yet, I'll sync up with the happenings here and start learning with the resources I can lay hold on.

**Comment by danielpassos** [comment]
I want to help on it to project not die

**Comment by KCErb** [comment]
Go @danielpassos! Keep up the good work :tada: :fireworks: :+1:

**Comment by donv** [comment]
Woohoo!  Welcome @danielpassos !  Pull request merged and commit rights given!

**Comment by donv** [comment]
OK, so @daneb has told me he is unable to fulfil the role as release manager.  Anybody else want to step up?  @danielpassos ?  Technically it is super easy, and I will be helping all the way.

**Comment by danielpassos** [comment]
@donv Sure. I can give it a try

**Comment by kinsomicrote** [comment]
What are the duties of a release manager?

**Comment by donv** [comment]
@danielpassos great!  We should get going on the 1.3.1 release right away.

@kinsomicrote the release makes the releases and the surrounding tasks like creating the release docs, announcing the release on the web and mailing lists, and managing the issues and milestones in the issue tracker.

There is a description of the release process in the wiki:  https://github.com/ruboto/ruboto/wiki/Release-process  It is not complete, but we will update it as needed.

Besides managing the releases, we need to make sure issues are responded to when they are submitted, and that no issues are forgotten over time.  For every new issue we should all strive to take a look at it and respond to the reporter so she knows the issues has been received, and then we should estimate the severeness of the issue to set one or more tags and put it in a milestone.  If it makes sense, we should also try to see who can fix the issues.

**Comment by kinsomicrote** [comment]
@donv Okay. What are the needed skills for a release manager? I would love to assist @danielpassos if possible.

**Comment by donv** [comment]
Hi @kinsomicrote !

Sorry for not replying earlier.  The release manager needs to communicate with the other team members to check if they are ready for release.  Then manage the issues by moving them to the correct GitHub milestone.  Then run the simple commands to do the actual gem release as described in https://github.com/ruboto/ruboto/wiki/Release-process .

**Comment by donv** [comment]
Looks like we are moving forward with the Ruboto 1.3.1 release.  @danielpassos will be doing the release.  Woohoo!  :+1:

**Comment by danielpassos** [comment]
I'm on it!

**Comment by donv** [comment]
Well done, @danielpassos !  Ruboto 1.3.1 is out!

**Comment by danielpassos** [comment]
http://ruboto.org/news/2015/10/14/Ruboto-1.3.1-release-doc.html

**Comment by daneb** [comment]
Well done Daniel!
