### ISSUE TITLE
rake install error

### ISSUE THREAD

**Issue by 3snail** [ruboto/ruboto#736]
when i run this command in the termianl, it show me errors
"
BUILD FAILED
/usr/local/lib/android-sdk-linux/tools/ant/build.xml:649: The following error occurred while executing this line:
/usr/local/lib/android-sdk-linux/tools/ant/build.xml:694: Execute failed: java.io.IOException: Cannot run program "/home/administrator/ruboto/splash/${aapt}": error=2, no such file or dictionary
....................
"
my machine is ubuntu14 64bit,and i have installed ia32-libs,and so on
android build-tools version 23.0.0-preview

how can i do ?

**Comment by daneb** [comment]
Looks like aapt is missing from your PATH.

Can you try run `aapt` from your terminal?

**Comment by 3snail** [comment]
thanks daneb answer,  and i have solved the problem。

i updated /usr/local/lib/android-sdk-linux/tools/ant/build.xml,and add 
<property name="aapt" location="/usr/local/lib/android-sdk-linux/build-tools/23.0.0-preview/aapt" /><property name="dx" location="/usr/local/lib/android-sdk-linux/build-tools/23.0.0-preview/dx" />
<property name="zipalign" location="/usr/local/lib/android-sdk-linux/build-tools/23.0.0-preview/zipalign" />

i have added "/usr/local/lib/android-sdk-linux/build-tools/23.0.0-preview" in env, why the system does't konw where the aapt is

**Comment by daneb** [comment]
Glad to hear!
