### ISSUE TITLE
Game Frameworks?

### ISSUE THREAD

**Issue by ashes999** [ruboto/ruboto#739]
Hi,

Are there any known/mature/stable game frameworks for Ruboto?

Gosu-Android is out of service (no longer maintained). It wrapped around Android graphics libraries, which is an approach others can take. I also had something working with OpenGL, but I didn't go far with that.

**Comment by daneb** [comment]
Hi

Unfortunately I'm not aware of any.
Perhaps @donv may have more input.

Dane

**Comment by donv** [comment]
Gosu-Android was the only one I was aware of.

**Comment by ashes999** [comment]
That's unfortunate. Thanks for the update.
