### ISSUE TITLE
How can I help? (sumanthkrishna)

### ISSUE THREAD

**Issue by sumanthkrishna** [ruboto/ruboto#744]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto: Currently working on Ionic based hybrid applications. With little experience on core Java and good experience with Ruby all the way!

My experience with HTML, CSS, JavaScript, and Jekyll: Pretty good with UI technologies

My experience using git and GitHub: Well I have been using the Git and Git based tools right from it's starting as SCM.

My other interests and passions: Apart development I love to do documentation, writing DIY kits for developers. I equally love to spend more in travel, watching movies, listening to music.

**Comment by danielpassos** [comment]
Hi @sumanthkrishna

Thanks for your interesting in the project. What do you think about see our list of issues and see if someone is interesting. In related I'm about review all wiki a help on it is really appreciated

**Comment by donv** [comment]
Hi @sumanthkrishna and @danielpassos !

Any follow up on this?

**Comment by danielpassos** [comment]
2 years without any comment. Going to close it
