### ISSUE TITLE
How can I help? (spiderOO7)

### ISSUE THREAD

**Issue by spiderOO7** [ruboto/ruboto#745]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:

My experience with HTML, CSS, JavaScript:

My experience using git and GitHub:

My other interests and passions:

**Comment by danielpassos** [comment]
Hi @spiderOO7 

Thanks for your interesting in the project. What do you think about see our list of issues and see if someone is interesting. In related I'm about review all wiki a help on it is really appreciated

**Comment by donv** [comment]
Hi @spiderOO7 and @danielpassos !

Any follow up on this?
