### ISSUE TITLE
Deploy ruboto within Gnuroot debian linux under Android OS

### ISSUE THREAD

**Issue by RubyRebbe** [ruboto/ruboto#750]
Hi,

I am running Gnuroot debian linux on my Digiland Android tablet. I would like to use ruboto inside of Gnuroot debian to deploy apps to the Android side of the same physical device. Is this possible? Without rooting? FYI ruboto works just fine on my ubuntu 14.04 laptop.

Just to let you know, on Gnuroot  I am running a complete ruby 2.2 development environment with rvm, git, rspec and so on. Great fun!

Thanks,
Tsvi Bar-David, San Francisco CA

**Comment by gfowley** [comment]
That GNURoot app looks interesting, I'll have to try it.

Have you been able to install Ruboto, create an application, and compile it ?

If so, here a couple of off-the-cuff suggestions to install the app:

A Ruboto app is usually installed over a USB connection between development system and Android device with the ```rake install``` command which uses the ```adb``` utility from the Android SDK. If a USB connection to Android can be emulated in GNURoot this usual method may just work. I suspect that's likely to require rooting the device and a custom USB device driver.

If GNURoot can access the Android filesystem, copy the application ```.apk``` file to it. Try the emulated SD card directory, it may not require root privileges. Then, from an Android terminal app, you may be able to run the ```pm``` shell command to install the .apk. 
Docs for the ```pm``` command (and others): http://developer.android.com/tools/help/shell.html#pm    

Finally, with a Google Play developer account you could deploy via the app store - but that would make for a very long dev/test cycle :-( .

Let us know how it goes.

**Comment by donv** [comment]
@RubyRebbe @gfowley Any progress on this?

**Comment by RubyRebbe** [comment]
Thanks for asking!

Ruboto works just fine cross-compiling from my Ubuntu 14.04 laptop to my
android tablet.  Have not been able to get it to work directly under
GNURoot on the tablet.

Tsvi

On Tue, Dec 22, 2015 at 3:33 PM, Uwe Kubosch <notifications@github.com>
wrote:

> @RubyRebbe <https://github.com/RubyRebbe> @gfowley
> <https://github.com/gfowley> Any progress on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruboto/ruboto/issues/750#issuecomment-166762218>.
>



-- 
Tsvi Bar-David
www.beitsimchah.net
SF, CA 94121
p:  415-387-6890
c:  415-806-2363
skype: tsvibardavid

**Comment by donv** [comment]
OK @RubyRebbe !  Really great to hear of your use of Ruboto!

I'll close this issue since I can't see anything we can do on this for now.

Please open a new issue if you can think of anything we can do to help.
