### ISSUE TITLE
ruboto app still requires ruboto-core even after doing the "ruboto gen jruby" command

### ISSUE THREAD

**Issue by irahey** [ruboto/ruboto#753]
Hi!

In the app directory of my ruboto app, I did the "ruboto gen jruby" command. However, when I do the rake install start, it still shows the screen telling that I need to install ruboto core.

I tried the the command "rake update_scripts" and it still does not work
I added the "require 'jruby-jars'" line at the top of my src/main.rb file, but it still requires my device to install ruboto core. 

I tried doing applying the "ruboto gen jruby" command and the "rake install start" and "rake update_scripts" commands with the tutorial_touch (https://github.com/ruboto/ruboto/wiki/Tutorial%3A-write-a-gosu-game), but it still returns me the Ruboto core screen.

Am I missing a step? Thanks

**Comment by gfowley** [comment]
Hi Ira,

Issue #739 mentions gosu-android (used by the Gosu game tutorial) is no longer maintained.

However, issue #748 is about an alternative [tutorial](https://github.com/ruboto/ruboto/wiki/Tutorial:-Write-a-libGDX-game).

Good luck.
-gf-

**Comment by kematy** [comment]
app start error

**Comment by kematy** [comment]
I do not know what causes the start error, someone said the long path name or file name has Spaces, but I do not have these cases

**Comment by kematy** [comment]
I had installed ruboto-core,app still ask me to install ruboto-core.
