### ISSUE TITLE
Allow "ruboto setup --update" to update HAXM if a new version is available

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#756]
Currently `ruboto setup` will download and install HAXM if it is missing.  `ruboto setup` will also list the current version as "old".

`ruboto setup` should add proper version comparison and download and install a newer version if it is available.

Anyone up for it?

**Comment by daneb** [comment]
I can take a stab at it !

**Comment by daneb** [comment]
Sorry Donv, just saw the "labels" - would your prefer a newcomer to tackle?

**Comment by daneb** [comment]
@donv Are you happy if I go ahead with this? Or would you like a newcomer to ruboto?

**Comment by donv** [comment]
@daneb Sorry for the late answer.  GitHub did not notify me.  I don't know why not.

Please go ahead!  The label is to guide newcomers, not to hinder the more experienced :smile:

**Comment by donv** [comment]
Hi @daneb !

Any progress?

**Comment by danielpassos** [comment]
Hey @donv not sure if I understand what is the problem. Could you check if it's related of this fix => https://github.com/ruboto/ruboto/commit/a99913502a239cc8f8952aa343d898620482413b

**Comment by donv** [comment]
@danielpassos the "problem" is that if we find an old version of HAXM installed, we just leave it as it is.  We should download and install a new version if it is available.

**Comment by danielpassos** [comment]
Gotcha. I'll try simulate that

**Comment by daneb** [comment]
@donv Just started. Do we need to download and install a new version of Intel HAXM since it comes with the SDK, but rather check if (OS_INTEL_HAXM < CURRENTLY_USED_SDK_INTEL_HAXM) ?

**Comment by donv** [comment]
I would prefer `ruboto setup -y --update` to download and install HAXM if a newer version is available from the Android SDK site.

Alternatively, we can warn that a newer version is available.  Then the developer can download and install the new version herself manually.  Or maybe just download and let Ruboto install it.

Or use a new command `ruboto update setup` and/or `ruboto update haxm` to let Ruboto download and install.

`ruboto setup -y --update` is still my favourite.

I am on board with anything you decide.  I personally miss a simple update path for HAXM using Ruboto.

**Comment by daneb** [comment]
Thanks Don, setup -y sounds reasonable to me!

**Comment by daneb** [comment]
@donv scratch that -> https://software.intel.com/sites/default/files/haxm-macosx_r05.zip   ;)

**Comment by daneb** [comment]
Hi @donv 

Here is a look at the direction I am going - what do you think?

https://github.com/ruboto/ruboto/compare/db_haxm?expand=1

**Comment by donv** [comment]
Looks good.

I generally prefer "update" to "upgrade".

Why is an "--upgrade-haxm" option needed for "ruboto gen app" ?

**Comment by daneb** [comment]
Gen app was a previous path, will remove it.

Thanks Uwe, will keep going!

**Comment by daneb** [comment]
@donv Do you have any recommendations around getting Intel HAXM installation package? That is, it's format is like such and there is unfortunately no repository reference:
 https://software.intel.com/sites/default/files/haxm-macosx_r05.zip

These are my options, 
1. Depend on new Android SDK UPDATE for Intel HAXM upgrade
2. Use a regex to "retry" till it finds a working URL version (eg. r03.zip, r05.zip)
3. Use a configuration file that contains URL hardcoded
4. Use an input parameter along with upgrade parameter to specify the version to upgrade too

Thanks
Dane

**Comment by donv** [comment]
I have not looked at this for a while, but we should be able to extract the correct download URL from the android XML files.  We (used to?) do this for the initial installation of HAXM.  We should be able to do the same for updates.

**Comment by daneb** [comment]
I initially checkout out the default repository[1-10].xml but did not find it there. But after some tracking down, found it's location. 
https://dl-ssl.google.com/android/repository/extras/intel/addon.xml

Cool, will use that!

**Comment by donv** [comment]
Nice!

**Comment by daneb** [comment]
@donv finished the implementation - busy working on testing. Hope to be done soon.

**Comment by donv** [comment]
Great @daneb !  Keep it up!

**Comment by donv** [comment]
Hi @daneb !

I am testing master now, and it seems to always install HAXM when I run `ruboto setup -y`.  I would expect it to not install anything the second time I run it, and display the current version as 1.1.1 and report "Ruboto setup is OK".

```
$ ruboto setup -y
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Intel HAXM               : Old   /1.1.1
Android SDK Command adb  : Found
Android SDK Command dx   : Found
Platform SDK android-16  : Found

    !!! Ruboto setup is NOT OK !!!

HAXM not installed.
Mounting the HAXM install image
/dev/disk3          	GUID_partition_scheme          	
/dev/disk3s1        	Apple_HFS                      	/Volumes/IntelHAXM_1.1.1
Starting the HAXM installer.  Sudo password required.
ecx 7fbae3ff
edx 28100800
edx 28100800
No emulator instance exist!
haxm-isDowngrade: installed version of Intel HAXM found = 1.1.1; current version = 1.1.1
current version is the same or newer than existing one
Intel HAXM: This is a re-installation (chnage of memory limit)
installer: Warning - Intel Hardware Accelerated Execution Manager is already installed on this computer. If you continue installation, the Intel HAXM will be re-installed.
installer: Package name is Intel(R) Hardware Accelerated Execution Manager
installer: Upgrading at base path /
installer: The upgrade was successful.
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Intel HAXM               : Old   /1.1.1
Android SDK Command adb  : Found
Android SDK Command dx   : Found
Platform SDK android-16  : Found

    !!! Ruboto setup is NOT OK !!!

```

**Comment by daneb** [comment]
Sounds good - will add functionality to my existing change

**Comment by donv** [comment]
@daneb Any chance you can complete this this weekend?

**Comment by daneb** [comment]
Hi @donv 
I will do so!

**Comment by donv** [comment]
@daneb Submit a pull request as soon as you have something green in travis.  We need to make the changes as small as possible to make merging easy.

**Comment by donv** [comment]
Hi @daneb !

Looking good for closing this today?

**Comment by daneb** [comment]
Hi Uwe

I'm hoping to work on it tonight.

I'm at the last phase of installing the package after mounting the Image (bug).

If I can crack that will send a PR.

Dane

**Comment by donv** [comment]
Great!  Best of luck to you!  :smile:

**Comment by daneb** [comment]
Hi @donv 

Ok I've got a working upgrade to Intel HAXM in db_haxm. The git diff is ugly given indentation (which I want to fix). However it's not a PR because I've got some concerns around the size and complexity of the change.

So what I would like to do, 
a) Create a dark launch subset of functionality which won't affect existing functionality (Pull Request 1) (with tests)
b) Create another PR 2, with the changes that will give us the upgrade functionality with tests
c) Create PR 3 with tests to ensure Intel HAXM doesn't re-install if existing version matches current (setup -y as you suggested).

I would like to get (a) and (b) done before Christmas. 

Dane

**Comment by donv** [comment]
@daneb Sounds good.

We will release on Christmas eve, 24th of December.  Make sure we have green builds then.

Looking forward to PR1 and PR2.  :smile:

BTW: Don't change the Ruboto version on the branch.  We change the version on master only.

**Comment by daneb** [comment]
Hi @uwe

Added in change for Dark Launch.
Awaiting CI.

Will keep you in the loop.

D

**Comment by daneb** [comment]
Hi @donv 

Struggling to get tests to run on my machine.
My Dark Launch branch is ready, manually tested and passing in CI.

Shall I do a PR? db_haxm_dark

Dane

**Comment by donv** [comment]
@daneb Yes!  Go for it!

**Comment by donv** [comment]
@daneb What does "dark launch" mean?

**Comment by daneb** [comment]
Hi @uwe

By dark launch I mean that PR will setup for the new feature but not make
it accessible.
So I've put on the building blocks in place in this first PR.

I've got the tests running yeah! But our coverage for command/util/setup.rb
is near non-existent.
I will issue PR and then try add some tests to the next PR which will
contain the --update for HAXM.

Thanks
D

**Comment by daneb** [comment]
@donv  Please find PR
https://github.com/ruboto/ruboto/pull/772/files

Will follow up tonight with the second with some basic tests

**Comment by donv** [comment]
The PR looks good!  Merge it, or I will!  :smile:

**Comment by donv** [comment]
Hi @daneb !

Everything going well?

**Comment by daneb** [comment]
Hi @uwe

Just about to start, let you know in a short while ;)

**Comment by daneb** [comment]
Hi @uwe

Need to crash now, 1:00 AM on this side.
Hopefully CI says YES.

Then we can pick it up tommorrow?

Dane

**Comment by donv** [comment]
The test that failed earlier, passed now :smile:  :+1: 

Midnight here in Norway :smile: 

We'll pick it up in the morning.

**Comment by daneb** [comment]
Sleep well ;)

**Comment by donv** [comment]
Bummer!  The test failed even if it handled not being able to install on Linux.

Anyway, sleep well :zzz:

**Comment by daneb** [comment]
Hi @Uwe

Travis is failing again.
For some reason I cannot view the reason or error, it pretends like its
going to load the error but nothing ever shows up.
You have similar problems?

Dane

**Comment by donv** [comment]
I am trying to reproduce locally now.  Can you reproduce in your environment?

@daneb Maybe we could chat on IRC #ruboto or https://gitter.im/ruboto/ruboto ?  It is a bit quicker.
