### ISSUE TITLE
How can I help? (NAVNEETOJHA)

### ISSUE THREAD

**Issue by NAVNEETOJHA** [ruboto/ruboto#758]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto: 
I am having 2 years of experience in Java and an year of experience in Ruby, and new for android, but I having great learning power, so it will take no time for me to learn android also.

My experience with HTML, CSS, JavaScript, and Jekyll:
Almost from last 4 years I am working on HTM, CSS and JavaScript

My experience using git and GitHub: 4 years of experience using git includes github, bitbucket and these days I am using gitlab

My other interests and passions: I love blogging and love to read stories of startup ventures.

**Comment by donv** [comment]
Hi @NAVNEETOJHA !

Welcome to the project!  Feel free to look around the project and browse the documentation.

Step one for contributing is to get Ruboto installed and completing your first tutorial.  Check out the WIKI and go through the Getting Started section.  Report back here your successes and problems :)

https://github.com/ruboto/ruboto/wiki
https://github.com/ruboto/ruboto/wiki/Getting-started

**Comment by donv** [comment]
Hi @NAVNEETOJHA !

How are you coming along with Ruboto?

**Comment by NAVNEETOJHA** [comment]
Hey, I have just started working on it, will tell you my experience soon.

Thanks

**Comment by danielpassos** [comment]
About 2 years without any comment, I'm going to close it, feel free to reopen, contributing is more than welcome.
