### ISSUE TITLE
JDK 7

### ISSUE THREAD

**Issue by joeymetal** [ruboto/ruboto#761]
https://edelivery.oracle.com/otn-pub/java/jdk/7/jdk-7-windows-x64.exe
this linkk not work 
ruby -S ruboto setup or ruboto setup 
do you do haven't a private repository?

**Comment by daneb** [comment]
Why do you need this link? Can you show me a screenshot or paste error message?

If you do need it - it's unsupported.

http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html

Dane

**Comment by donv** [comment]
Hi @joeymetal and @daneb !

Any news on this?

**Comment by daneb** [comment]
@joeymetal Please query again if still a problem

**Comment by joeymetal** [comment]
Hello @daneb and @donv  
the error was that was setting the path of java 7 wrong, but now it's all right thanks you
