### ISSUE TITLE
How can I help? (juanjogeta)

### ISSUE THREAD

**Issue by juanjogeta** [ruboto/ruboto#762]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:

I have worked with ruby for two years. I have used some technologies and gems and I have helped to create Bizneo.com

I have used Java in my studies, and a little of Android, but I'm not and expert.

My experience with HTML, CSS, JavaScript, and Jekyll:

I have experience with HTML, CSS and JS but not with Jekyll. I have used Jquery, CoffeeScript, Sass, HAML, SLIM and I'm learning Aurelia.

My experience using git and GitHub:

I always use git in my projects, with Bitbucket ot Github,

My other interests and passions:

I love web programming, especially RoR. I am doing an app www.betcomparing.com, although it is still very young.

I am 23 years old and I want to contribute in a big projects, I do not mind doing boring tasks.

Thanks!

**Comment by daneb** [comment]
Hello JuanJogeta

Welcome to the project! Feel free to look around the project and browse the
documentation.

Step one for contributing is to get Ruboto installed and completing your
first tutorial. Check out the WIKI and go through the Getting Started
section.

PS. During this process you may even find opportunities to update the
documentation or raise an issue with existing guides. Report back here your
successes and problems :)

https://github.com/ruboto/ruboto/wiki
https://github.com/ruboto/ruboto/wiki/Getting-started

**Comment by juanjogeta** [comment]
Thanks!

I'll try to do my best.

Cheers,
Juanjo

2015-12-11 9:32 GMT+01:00 Dane Balia <notifications@github.com>:

**Comment by daneb** [comment]
@juanjogeta please shout if there is anything we can assist with?

**Comment by juanjogeta** [comment]
@daneb Could you indicate me some issues in order to learn about ruboto, please? Thanks

**Comment by daneb** [comment]
Hello @juanjogeta 

Great stuff. If you have made some progress through the Getting Started, you could possibly tackle:
#778 or #779 

@donv would be of great assistance on those two if you need guidance.

Dane
