### ISSUE TITLE
can't create any apps. 

### ISSUE THREAD

**Issue by rayto** [ruboto/ruboto#763]
Here is the terminal:

```
Generating Android test project QuickStart in /home/rayto/ruboto-projects/quick_start...
Found main project package: org.ruboto.examples.quick_start
Found main project activity: QuickStartActivity
Found main project target: Android 4.1.2
Created project directory: /home/rayto/ruboto-projects/quick_start/test
Created directory /home/rayto/ruboto-projects/quick_start/test/src/org/ruboto/examples/quick_start
Added file /home/rayto/ruboto-projects/quick_start/test/src/org/ruboto/examples/quick_start/QuickStartActivityTest.java
Created directory /home/rayto/ruboto-projects/quick_start/test/res
Created directory /home/rayto/ruboto-projects/quick_start/test/bin
Created directory /home/rayto/ruboto-projects/quick_start/test/libs
Added file /home/rayto/ruboto-projects/quick_start/test/AndroidManifest.xml
Added file /home/rayto/ruboto-projects/quick_start/test/build.xml
Added file /home/rayto/ruboto-projects/quick_start/test/proguard-project.txt
Done
update_test: target_level: 16

Copying files:
.gitignore...Done.
Rakefile...Done.
ruboto.yml...Done.
assets...Done.
rakelib...Done.
res/layout...Done.
test...Done.
Copying ruboto/version.rb...Done.
Copying additional ruboto script components...Done.
Copying icons...Done.
Ruboto java classes...Done.
Ruboto java test classes...Done.
Loading Android API...Done.
Generating methods for RubotoActivity...Done. Methods created: 61
Generating methods for RubotoService...Done. Methods created: 10
Generating methods for RubotoBroadcastReceiver...Done. Methods created: 1
rake aborted!
Errno::ENOENT: No such file or directory - adb version
/home/rayto/ruboto-projects/quick_start/rakelib/ruboto.rake:39:in ``'
/home/rayto/ruboto-projects/quick_start/rakelib/ruboto.rake:39:in `<top (required)>'
(See full trace by running task with --trace)
Generating the default Activity and script...Added file /home/rayto/ruboto-projects/quick_start/src/org/ruboto/examples/quick_start/QuickStartActivity.java.
Added file /home/rayto/ruboto-projects/quick_start/src/quick_start_activity.rb.
Added file /home/rayto/ruboto-projects/quick_start/test/src/quick_start_activity_test.rb.
Done.

Hello, QuickStart
```

what does this part mean and how do I fix it?

```
Errno::ENOENT: No such file or directory - adb version
/home/rayto/ruboto-projects/quick_start/rakelib/ruboto.rake:39:in ``'
/home/rayto/ruboto-projects/quick_start/rakelib/ruboto.rake:39:in `<top (required)>'
(See full trace by running task with --trace)
```

 Thanks

**Comment by donv** [comment]
Hi @rayto !

The error message indicates that the `adb` command is not on your path.  The error message should be better.

What does `ruboto setup -y` output?

**Comment by rayto** [comment]
it seems to be ok.
```
rayto@Time:~/ruboto-projects$ ruboto setup -y
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Android SDK Command adb  : Found
Android SDK Command dx   : Found
Platform SDK android-16  : Found

    *** Ruboto setup is OK! ***
```

**Comment by donv** [comment]
Hi @rayto !

Are you sure the app is not created?  The output suggests that it is.  Is there a directory called `quick_start`?  If so, try to go into that directory and build using `rake debug`.

**Comment by donv** [comment]
Hi @rayto !

Was the directory `quick_start` created?  Were you able to build the project?

**Comment by rayto** [comment]
Hi, I'm back working on this again and I'm still receiving this same error.
The project is created on the computer, I just can't enter the rake commands without getting this error.
Any suggestions would be much appreciated.
Thanks!

rayto@Time:~/existence$ rake debug
rake aborted!
Errno::ENOENT: No such file or directory - adb version
/home/rayto/existence/rakelib/ruboto.rake:39:in ``'
/home/rayto/existence/rakelib/ruboto.rake:39:in `<top (required)>'
(See full trace by running task with --trace)
`

**Comment by donv** [comment]
What does `ruboto setup` **inside the project** say?

What does `which adb` day?

What version of ruboto are you using now?

**Comment by rayto** [comment]
`ruboto setup`
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Android SDK Command adb  : Found
Android SDK Command dx   : Found
Platform SDK android-16  : Found
  *** Ruboto setup is OK! ***

`which adb`
/home/rayto/android-sdk-linux/platform-tools/adb

`ruboto --v`
1.4.1

**Comment by donv** [comment]
Is the error message still exactly the same?

**Comment by rayto** [comment]
Yes,

**Comment by donv** [comment]
Line 39 in `rakelib/ruboto.rake` tries to run the command `adb version`.  What happens if you run that command directly instead of `rake debug`?

**Comment by rayto** [comment]
rayto@Time:~$ adb version
bash: /home/rayto/android-sdk-linux/platform-tools/adb: No such file or directory

**Comment by donv** [comment]
OK, so there is your problem.

**Comment by rayto** [comment]
Ok, whats the solution? and thanks

**Comment by donv** [comment]
Try updating your toolchain using the `android`command.  It will start the graphical package manager.

**Comment by donv** [comment]
I don't have the solution, yet :smile: Just happy we have isolated the problem.

**Comment by rayto** [comment]
I think you (we) are on to something

**Comment by rayto** [comment]
I'll get back later but its just updating my SDK

**Comment by donv** [comment]
OK

**Comment by rayto** [comment]
Ok so now I says:
`Android SDK platform tools not in PATH (adb command not found).`
Do you know how this could be fixed? it seem straight forward

**Comment by donv** [comment]
Closing this issue since it relates to Ruboto 1.x.  Ruboto 2 now uses Android Studio with a much simpler setup.  A guide to getting started is in the README.
