### ISSUE TITLE
Publish ruboto gem to AWS S3

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#774]
For successful builds in travis, we should publish the ruboto gem to AWS S3 or other free download site for people to try out fixes.

cloning the source and running `rake reinstall` should not be hard, but downloading is even easier :smile: .

**Comment by OrthoDex** [comment]
Hi!

I reckon you are looking for something like this to be setup:
[RubyGems](https://docs.travis-ci.com/user/deployment/rubygems/)
[S3](https://docs.travis-ci.com/user/deployment/s3/)

Do you mind if I take this up?

**Comment by donv** [comment]
Hi @OrthoDex !

That would be great.  Try to integrate this into the `release` Rake task.

**Comment by OrthoDex** [comment]
Alright, I'll issue a PR over the weekend. :smile:

**Comment by OrthoDex** [comment]
Hey @donv 
Issued a PR at #835

**Comment by OrthoDex** [comment]
Hey @donv , is this PR good to go?

**Comment by donv** [comment]
Hi @OrthoDex !

I left comments on the PR.
