### ISSUE TITLE
Setup never finds Platform SDK

### ISSUE THREAD

**Issue by ahills** [ruboto/ruboto#785]
I already have the `android-16` platform SDK installed, but `ruboto setup` could not find it. I let it install, and it still cannot find it:

```
Installing Archives:
  Preparing to install archives
  Downloading SDK Platform Android 4.1.2, API 16, revision 5
  Installing SDK Platform Android 4.1.2, API 16, revision 5
    Installed SDK Platform Android 4.1.2, API 16, revision 596%)
  Downloading ARM EABI v7a System Image, Android API 16, revision 4
  Installing ARM EABI v7a System Image, Android API 16, revision 4
    Installed ARM EABI v7a System Image, Android API 16, revision 499%)
  Downloading Intel x86 Atom System Image, Android API 16, revision 2
  Installing Intel x86 Atom System Image, Android API 16, revision 2
    Installed Intel x86 Atom System Image, Android API 16, revision 299%)
  Done. 3 packages installed.
Platform SDK android-16  : Not found
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Intel HAXM               : Old   6.0.1/
Android SDK Command adb  : Found
Android SDK Command dx   : Found
Platform SDK android-16  : Not found

    !!! Ruboto setup is NOT OK !!!

```

It will download, install, and fail to find the SDK as many times as I run `ruboto setup`. How can I correct this behavior?

**Comment by donv** [comment]
Hi @ahills !

Thanks for the report!

What platform are you on (Windows/Linux/OS X) ?

What is the location of your Android installation?

**Comment by ahills** [comment]
OK, figured it out. On OS X, when installing the Android SDK, it installs `adb`, `android`, etc into `/usr/local/bin`, but the platform SDK check uses the location of the `android` executable to discover the `platform` directory: `"#{@android_loc}/../../platform"`. I have worked around this problem by putting `$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools` in the *front* of my `$PATH` rather than at the end.

Would you accept a PR that falls back on using `$ANDROID_HOME` when the current method fails?

**Comment by donv** [comment]
Yes, absolutely!  We already use ANDROID_HOME for locating several components.  Looking forward to you PR :)

**Comment by ahills** [comment]
#786—thanks for the snappy response!

**Comment by donv** [comment]
Hi @ahills !

Do you think you could write a test that fails without your fix and succeeds with the fix?

Commit rights will be given if you do. :smile: 

We have existing `ruboto setup`tests in `test/ruboto_setup_test.rb`.  If you decide to go forward, you can add your tests there, or find a better place. :smile:

**Comment by ahills** [comment]
Sorry, somehow I missed this reply! I will try to find time to do it this week.

**Comment by donv** [comment]
Great!  Looking forward to it!
