### ISSUE TITLE
How can I help? (franciscoGPS)

### ISSUE THREAD

**Issue by franciscoGPS** [ruboto/ruboto#788]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:
Im a Java Developer with 3 years in experience. Im relative new to Rails and android, 1+ year
My experience with HTML, CSS, JavaScript, and Jekyll:
Im not very good with frontend languages but I know and understand'em well ...
My experience using git and GitHub:
Relatively new. The same as with rails, like one year and a half. I'am not a newbie, though sometimes I struggle a little. Anything is on google. You just need to google deeper or more accurate.
My other interests and passions:
I am a runner and passionate for new techs like android, and rails. I also like to play guitar and read. I am planning to study a masters abroad later this year. I can help with this project as much as I can

**Comment by donv** [comment]
Hi @franciscoGPS !

Thanks for your interest in the Ruboto project!

You should start by setting up your Ruboto development environment and create run the default app:

https://github.com/ruboto/ruboto/wiki/Setting-Up-a-Ruboto-Development-Environment

The complete a few of the tutorials:

https://github.com/ruboto/ruboto/wiki/Tutorials-and-examples

Along the way file issues in this tracker when you see things that can be improved.  Any suggestions are welcome.

When you are familiar with the basics of Ruboto, look at the issues in this tracker and see if there is anything you would like to work on.  Some issues are marked "newcomer friendly", but please pick anything you want.  Be sure to ask if you have any questions.

Happy hunting!

**Comment by danielpassos** [comment]
About a year without any comment, I'm going to close it, feel free to reopen, contributing is more than welcome.
