### ISSUE TITLE
How can i help?

### ISSUE THREAD

**Issue by AdepuRamMohan** [ruboto/ruboto#799]
How can i contribute to ruboto?

**Comment by hovancik** [comment]
https://github.com/ruboto/ruboto/wiki/Contributing

**Comment by zackp30** [comment]
(Closing due to non-issue)

**Comment by zackp30** [comment]
Whoops, sorry, I didn't follow convention! :)

**Comment by donv** [comment]
Hi @AdepuRamMohan !

Have you found anything you want to contribute to Ruboto?

**Comment by danielpassos** [comment]
About a year without comment. I'm going to close it. Feel free to reopen it. Contributors are more than welcome.
