### ISSUE TITLE
Error Came Back : Android SDK command dx Not found

### ISSUE THREAD

**Issue by rajcybage** [ruboto/ruboto#801]
I amusing Ubuntu 14.04 LTS and android-17. I did `ruboto setup` I did not find any folder name build_tools onthe sdk folder. and I have export all the path in .bashrc as per guide. I have also seen https://github.com/ruboto/ruboto/pull/454

**Comment by zackp30** [comment]
What does `which dx` return?

**Comment by StanisLoveSid** [comment]
`sudo apt-get install dx`

**Comment by donv** [comment]
Closing since this relates to Ruboto 1.x.  Ruboto 2 now uses Android Studio with a much simpler setup.
