### ISSUE TITLE
Not in wiki: Installing apk's to android phone through Wifi

### ISSUE THREAD

**Issue by ipepe** [ruboto/ruboto#804]
Why it's not written anywhere?
UNAuthorized USB device:

```
MBP-A1278-ipepe:~ patryk$ adb devices
List of devices attached
0b06b8360328c13a    unauthorized
```

Authorized USB device:

```
MBP-A1278-ipepe:~ patryk$ adb devices
List of devices attached
0b06b8360328c13a    device
```

While connected to USB, start adb server on port 5555

```
MBP-A1278-ipepe:~ patryk$ adb tcpip 5555
restarting in TCP mode port: 5555
```

Disconnect USB from Your android device. Check it's IP address and connect Your ADB through wifi: 

```
MBP-A1278-ipepe:~ patryk$ adb connect 192.168.0.50
connected to 192.168.0.50:5555
```

Now if You list devices You can see device connected to ADB:

```
MBP-A1278-ipepe:~ patryk$ adb devices
List of devices attached
192.168.0.50:5555   device
```

And You can easly do:

```
MBP-A1278-ipepe:ruboto-one patryk$ rake reinstall start
Uninstalling package pl.ipepe.ruboto.one
Success
adb shell date -s 20160424.193225
Sun Apr 24 19:32:23 CEST 2016
Installing package pl.ipepe.ruboto.one
69 KB/s (75682 bytes in 1.061s)
        pkg: /data/local/tmp/RubotoOne-debug.apk
Success
```

**Comment by donv** [comment]
Hi @ipepe!

The wiki is open for contributors.  Could you add this to a page?

**Comment by ipepe** [comment]
Currently I am engaged in ruboto project. But if anyone has questions, feel free to poke me.

**Comment by UnsnappedKhan8** [comment]
I'm interested in what you have to say and the code you had to write

**Comment by ipepe** [comment]
It was long time ago, pretty much everything You need to know is in the opening comment

**Comment by UnsnappedKhan8** [comment]
When I was a kid I wrote a new code that I think API follows along with everyone else

**Comment by donv** [comment]
Ruboto 2 now uses Android Studio tooling.  No special Ruboto tooling needed for installing an app.
