### ISSUE TITLE
How well does Ruboto work with Shoes 4?

### ISSUE THREAD

**Issue by Merovex** [ruboto/ruboto#822]
I'm looking to develop something cross-platform. It looks like my option is JRuby, with Ruboto and Shoes. However, I'm not sure whether these two implementations are compatible. Any thoughts?

**Comment by KCErb** [comment]
I've worked a little with Ruboto and used to do a lot more for the Shoes community than I do nowadays. 

As is, you'll be writing totally separate code for your Shoes and Ruboto apps, but one of the design features of Shoes 4 is that it has a frontend and backend. The frontend contains the Shoes DSL and the backend implements it. Right now an SWT backend is being developed, but the team is definitely open to other backends such as Ruboto.
 
So you could start off by trying to create a Ruboto backend for Shoes. I for one would be really excited about that kind of thing, and if I get time in the future to get back to open-source development I know that that kind of a project would be at the top of my list.

**Comment by donv** [comment]
I'll mark this one as answered.
