### ISSUE TITLE
Start using the `sdkmanager` to install packages

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#825]
It seems `tools/bin/sdkmanager` is a duplicate but better tool for installing Android packages.

**Comment by MaxPleaner** [comment]
This is more essential now as the `android` command has been removed in the SDK. See https://github.com/ruboto/ruboto/issues/838

**Comment by donv** [comment]
Closing this issue since it relates to Ruboto 1.x.  Ruboto 2 now uses Android Studio with a much simpler setup.  A guide to getting started is in the README.
