### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by Maikhaa** [ruboto/ruboto#831]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:
I have basic Ruby knowledge and would love to learn more.

My experience with HTML, CSS, JavaScript, and Jekyll:
I've been working with HTML & CSS for sometime and I'm now working on a API doc project in Jekyll.

My experience using git and GitHub:
Basic.

My other interests and passions:
Helping make technology accessible and working on creating a positive social impact with it.

**Comment by donv** [comment]
Hi @Maikhaa !

We have several tasks for improving our home page at http://ruboto.org/

Would you like to help out?

**Comment by Maikhaa** [comment]
Hi @donv! Where can I find more information?

**Comment by donv** [comment]
Hi @Maikhaa !

Sorry for the late reply.  Lots to do.

You can find the tasks here in the tracker.  Any tasks are OK for you to work on.  If you scan the issues, and maybe select by label (newcomer friendly, documentation, etc.), I'm sure you will find something you can do.

When you find a task you find interesting, put a comment on it to let people know you are looking at it.

If you have any questions, please ask.  I'll leave this issue open for a while so you have a place to ask?

**Comment by donv** [comment]
Hi @Maikhaa!

Did you find anything you think you can contribute with?

**Comment by danielpassos** [comment]
About a year without any comment, I'm going to close it, feel free to reopen, contributing is more than welcome.
