### ISSUE TITLE
Hello, How do I compile？

### ISSUE THREAD

**Issue by vaemc** [ruboto/ruboto#832]
Thank you developers,Thanks brother！！

What parameters are needed，How do I compile？

![4](https://cloud.githubusercontent.com/assets/16460137/22618703/893740da-eb1e-11e6-986e-2af250c977ef.png)

**Comment by vaemc** [comment]
I love all of you  forever！！

**Comment by donv** [comment]
Hi @vaemc !

Did you figure this out?

**Comment by danielpassos** [comment]
@vaemc  

```shell
[passos]: ~/Development/Projects/Opensource/ruboto [ruby-2.3.0@ruboto] [git:master]
→ rake
Generating ruboto-2.0.0.dev.gem
```
