### ISSUE TITLE
#1 I can't generate simple app [SOLVED]; #2 error in util/verify.rb [I have a solution]

### ISSUE THREAD

**Issue by tomipoc** [ruboto/ruboto#839]
Hello,

I am getting this issue when I'm trying to generate a new project with ruboto.
I'm developing on WIndows 10. I have tried the current version 1.7.26, and and older 1.7.12 jruby, I have jdk 7 and 8 as well and android 19 revision, but I keep getting this error message (full generation process log): (I have found an another issue, see after the log:)

`c:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary>ruboto gen app --package org.ruboto.examples.ruboto_phone_homeapp

Generating Android app RubotoPhoneHomeapp in c:/Users/Pocok/Desktop/Szakdoga/mscszakdoka/rubydictionary/ruboto_phone_homeapp...
Created project directory: C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\src\org\ruboto\examples\ruboto_phone_homeapp
Added file C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\src\org\ruboto\examples\ruboto_phone_homeapp\RubotoPhoneHomeappActivity.java
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\res
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\bin
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\libs
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\res\values
Added file C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\res\values\strings.xml
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\res\layout
Added file C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\res\layout\main.xml
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\res\drawable-xhdpi
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\res\drawable-hdpi
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\res\drawable-mdpi
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\res\drawable-ldpi
Added file C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\AndroidManifest.xml
Added file C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\build.xml
Added file C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\proguard-project.txt
Removed file src/org/ruboto/examples/ruboto_phone_homeapp/RubotoPhoneHomeappActivity.java
Removed file res/layout/main.xml
Done

Adding RubotoActivity, RubotoDialog, RubotoService, and SDK versions to the manifest...Done.

Generating Android test project RubotoPhoneHomeapp in C:/Users/Pocok/Desktop/Szakdoga/mscszakdoka/rubydictionary/ruboto_phone_homeapp...
Found main project package: org.ruboto.examples.ruboto_phone_homeapp
Found main project activity: RubotoPhoneHomeappActivity
Found main project target: Android 4.4.2
Created project directory: C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\test
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\test\src\org\ruboto\examples\ruboto_phone_homeapp
Added file C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\test\src\org\ruboto\examples\ruboto_phone_homeapp\RubotoPhoneHomeappActivityTest.java
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\test\res
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\test\bin
Created directory C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\test\libs
Added file C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\test\AndroidManifest.xml
Added file C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\test\build.xml
Added file C:\Users\Pocok\Desktop\Szakdoga\mscszakdoka\rubydictionary\ruboto_phone_homeapp\test\proguard-project.txt
Done
update_test: target_level: 19

Copying files:
.gitignore...Done.
Rakefile...Done.
ruboto.yml...Done.
assets...Done.
rakelib...Done.
res/layout...Done.
test...Done.
Copying ruboto/version.rb...Done.
Copying additional ruboto script components...Done.
Copying icons...Done.
Ruboto java classes...Done.
Ruboto java test classes...Done.
Copying c:/jruby-1.7.12/lib/ruby/gems/shared/gems/jruby-jars-1.7.25/lib/jruby-core-1.7.25.jar to libs...Done.
Setting JUMBO dex file format...Done.
Copying dx.jar to libs...Done.
Removing unneeded classes from jruby-core-1.7.25.jar...F, [2017-05-05T01:43:35.876000 #11408] FATAL -- : Compile failed (RuntimeError)
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/ruboto-1.6.1/lib/ruboto/util/update.rb:693:in `reconfigure_jruby_core'
org/jruby/RubyDir.java:329:in `chdir'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/ruboto-1.6.1/lib/ruboto/util/update.rb:454:in `reconfigure_jruby_core'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/ruboto-1.6.1/lib/ruboto/util/log_action.rb:13:in `log_action'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/ruboto-1.6.1/lib/ruboto/util/update.rb:451:in `reconfigure_jruby_core'
org/jruby/RubyDir.java:329:in `chdir'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/ruboto-1.6.1/lib/ruboto/util/update.rb:449:in `reconfigure_jruby_core'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/ruboto-1.6.1/lib/ruboto/util/update.rb:440:in `reconfigure_jruby_libs'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/ruboto-1.6.1/lib/ruboto/util/update.rb:212:in `update_jruby'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/ruboto-1.6.1/lib/ruboto/commands/base.rb:139:in `run'
org/jruby/RubyDir.java:329:in `chdir'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/ruboto-1.6.1/lib/ruboto/commands/base.rb:124:in `run'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `run'
org/jruby/RubyKernel.java:1264:in `catch'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/main-5.3.2/lib/main/program/class_methods.rb:143:in `run'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/ruboto-1.6.1/lib/ruboto/commands/base.rb:28:in `main'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/ruboto-1.6.1/bin/ruboto:11:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
c:\jruby-1.7.12\bin\ruboto:23:in `(root)'`

Another issue: in the util/verify.rb you have a function called 
`def` verify_manifest(reload: false)`
When I tried to run ruboto setup, I got error messages. Those were caused because instead of : you shoul use = when trying to add default value to a function parameter. I mean this:
`def` verify_manifest(reload = false)`

**Comment by tomipoc** [comment]
The first issue is solved by copying the android sdk folder to a folder without spaces.
The second one can be solved by my suggestion in the description.

**Comment by donv** [comment]
@tomipoc So, all solved, then?

**Comment by tomipoc** [comment]
Yes, these issues are solved. Now I'm facing a new issue.
When I create a new project (e.g.: ruboto gen app --package com.org.exampleapp) and I install it with **rake install start**, the app starts but it says i should install ruboto core. I have installed it, started it, then pushed the exit button. When I start the exampleapp again, the same "splash" activity starts and says I should install the ruboto core.. Do you have any idea what should I do? I'm using a Xiaomi Redmi Note 2 phone for test.

**Comment by donv** [comment]
Hi @tomipoc !

Try looking in your `adb logcat` output (or `rake log` if it works for you), and look for an Exception while loading JRuby.  Any exception loading JRuby results in the Ruboto Core download dialog.  I'd like to change this, but I am swamped with the JRuby 9K update.

**Comment by donv** [comment]
@tomipoc You could search for the string "Exception starting JRuby", maybe.

**Comment by tomipoc** [comment]
Thanks for the informations, I will check the logs. 
I downloaded the Ruboto IRB project and replaced the ruby script and maniest with my content and it works for now.
I will add my comment when I will have the logs.

**Comment by tomipoc** [comment]
I have another issue. I tried to create a new SQLiteOpenHelper class
 `class DatabaseHandler < android.database.sqlite.SQLiteOpenHelper`
and I have added a function to recreate the database:
```
       def recreate
		db = getWritableDatabase
		db.execSQL('DROP TABLE IF EXISTS ' + TABLE_DICTIONARY)
		onCreate(db)
		db.close
	end
```
On this line the app gets stuck:
`db = getWritableDatabase`

I got these in the log:
```
20170508 085214.682000 D/SQLiteDatabase(17765): beginTransaction()
20170508 085215.562000 I/art     (17765): Background sticky concurrent mark sweep GC freed 111908(5MB) AllocSpace objects, 2(40KB) LOS objects, 0% free, 63MB/63MB, paused 88.595ms total 722.901ms
20170508 085216.196000 I/art     (17765): Background partial concurrent mark sweep GC freed 38352(2028KB) AllocSpace objects, 2(300KB) LOS objects, 19% free, 64MB/80MB, paused 91.752ms total 631.484ms
20170508 085216.198000 D/OpenGLRenderer(17765): Flushing caches (mode 0)
20170508 085216.198000 D/OpenGLRenderer(17765): Flushing caches (mode 0)
20170508 085216.201000 D/OpenGLRenderer(17765): Flushing caches (mode 0)
20170508 085217.936000 I/art     (17765): Background sticky concurrent mark sweep GC freed 34018(2008KB) AllocSpace objects, 3(552KB) LOS objects, 0% free, 85MB/85MB, paused 88.699ms total 621.152ms
20170508 085218.642000 I/art     (17765): Background partial concurrent mark sweep GC freed 492712(22MB) AllocSpace objects, 1(184KB) LOS objects, 19% free, 65MB/81MB, paused 98.698ms total 703.059ms
20170508 085219.653000 I/art     (17765): Rejecting re-init on previously-failed class java.lang.Class<org.jruby.util.JavaNameMangler>
20170508 085220.577000 I/art     (17765): Background sticky concurrent mark sweep GC freed 36882(1748KB) AllocSpace objects, 1(184KB) LOS objects, 0% free, 86MB/86MB, paused 101.472ms total 667.596ms
20170508 085221.392000 I/art     (17765): Background partial concurrent mark sweep GC freed 392655(17MB) AllocSpace objects, 2(368KB) LOS objects, 18% free, 70MB/86MB, paused 122.975ms total 818.327ms
20170508 085222.354000 I/art     (17765): Rejecting re-init on previously-failed class java.lang.Class<org.jruby.util.JavaNameMangler>
```

Could you please help me to find out what can cause the problem?

**Comment by tomipoc** [comment]
I have another issue. I can't reach www.ruboto.org page in these days. Or is the page down?

**Comment by donv** [comment]
@tomipoc Please open separate issues in the tracker for separate problems.

**Comment by tomipoc** [comment]
@donv Sorry, I have opened a new issue for SQLiteOpenHelper issue.
