### ISSUE TITLE
Setup broken -- FATAL, SDK link cannot be found on download page.

### ISSUE THREAD

**Issue by nathanmp** [ruboto/ruboto#842]
My guess is that the expression used to find the SDK is incompatible with the updated Android Studio website, as it's been updated recently.

Trace:
`
/var/lib/gems/2.3.0/gems/ruboto-1.6.1/lib/ruboto/util/setup.rb:150:in 'get_android_sdk_version'
/var/lib/gems/2.3.0/gems/ruboto-1.6.1/lib/ruboto/util/setup.rb:525:in 'block (2 levels) in install_android_sdk'
/var/lib/gems/2.3.0/gems/ruboto-1.6.1/lib/ruboto/util/setup.rb:524:in 'chdir'
/var/lib/gems/2.3.0/gems/ruboto-1.6.1/lib/ruboto/util/setup.rb:524:in 'block in install_android_sdk'
/var/lib/gems/2.3.0/gems/ruboto-1.6.1/lib/ruboto/util/setup.rb:522:in 'chdir'
/var/lib/gems/2.3.0/gems/ruboto-1.6.1/lib/ruboto/util/setup.rb:522:in 'install_android_sdk'
/var/lib/gems/2.3.0/gems/ruboto-1.6.1/lib/ruboto/util/setup.rb:303:in 'install_all'
/var/lib/gems/2.3.0/gems/ruboto-1.6.1/lib/ruboto/util/setup.rb:24:in 'setup_ruboto'
/var/lib/gems/2.3.0/gems/ruboto-1.6.1/lib/ruboto/commands/base.rb:472:in 'run'
/var/lib/gems/2.3.0/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in 'block in run'
/var/lib/gems/2.3.0/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in 'catch'
/var/lib/gems/2.3.0/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in 'run'
/var/lib/gems/2.3.0/gems/main-5.3.2/lib/main/factories.rb:18:in 'run'
/var/lib/gems/2.3.0/gems/main-5.3.2/lib/main/factories.rb:25:in 'Main'
/var/lib/gems/2.3.0/gems/ruboto-1.6.1/lib/ruboto/commands/base.rb:28:in 'main'
/var/lib/gems/2.3.0/gems/ruboto-1.6.1/bin/ruboto:11:in '<top (required)>'
/usr/local/bin/ruboto:23:in 'load'
/usr/local/bin/ruboto:23:in '<main>'
`

**Comment by donv** [comment]
Yes, the web page has changed, again.  I have a fix for this.
