### ISSUE TITLE
Unable to create an app (Mac)

### ISSUE THREAD

**Issue by clfristoe** [ruboto/ruboto#843]
When I run the command "ruboto setup", everything is working properly: 

![screen shot 2017-06-26 at 11 03 42 am](https://user-images.githubusercontent.com/15655814/27553301-470801ee-5a5f-11e7-90ad-b4590bfeea72.png)

Going off of the Add a Menu tutorial, I then run: 
"ruboto gen app --package org.ruboto.examples.menu_example"
and I get this errror: 

![screen shot 2017-06-26 at 11 06 23 am](https://user-images.githubusercontent.com/15655814/27553384-89e34ca8-5a5f-11e7-9d8f-ab3c9dff360d.png)

Thank you in advance for your help!

**Comment by donv** [comment]
Hi @clfristoe !

Looks like the Android tooling has changed again.  I'll take a look as soon as I can, or you or someone else could investigate.

The issue to switch from the `android` tool to `sdkmanager` tool is #825 .  This looks like the `create project` command has moved as well, maybe to some Android Studio tool.

**Comment by toomus** [comment]
@clfristoe To fix app generator, download latest tools release where 'android' tool was available and paste all files from zip to your sdk/tools folder. It also fixes problem with ANT replaced with Grawl.

Link to working tools: 
 - Mac: https://dl.google.com/android/repository/tools_r25.2.5-macosx.zip
 - Windows: https://dl.google.com/android/repository/tools_r25.2.5-windows.zip
 - Linux: https://dl.google.com/android/repository/tools_r25.2.5-linux.zip

**Comment by donv** [comment]
Closing this issue since it relates to Ruboto 1.x.  Ruboto 2 now uses Android Studio with a much simpler setup.  A guide to getting started is in the README.
