### ISSUE TITLE
Why the website is down?

### ISSUE THREAD

**Issue by luisgal93** [ruboto/ruboto#846]

**Comment by donv** [comment]
Hi!

@headius can you check the domain settings for ruboto.org ?

**Comment by danielpassos** [comment]
@donv Any news on this?

**Comment by donv** [comment]
No news.  The domain is served by @headius , but I have no response from him.

**Comment by donv** [comment]
@headius ping ?

**Comment by headius** [comment]
Very sorry I missed this for so long! It was an IP address update on Github's end that I never fixed in the DNS records. It's updated now, the site works again, and the DNS change should propagate out shortly (1h TTL).
