### ISSUE TITLE
"ruboto setup" needs to update

### ISSUE THREAD

**Issue by fitmap** [ruboto/ruboto#849]
D:\>ruboto setup -y
D:/Ruby24/lib/ruby/gems/2.4.0/gems/main-5.3.2/lib/main/getoptlong.rb:73: warning: constant ::FALSE is deprecated
Java runtime             : Not found
Java Compiler            : Not found
Apache ANT               : Not found
Android Package Installer: Not found
Android SDK Manager      : Not found
Android Emulator         : Not found
Intel HAXM               : Not found
Android SDK Command adb  : Found
Android SDK Command dx   : Not found
Platform SDK android-19  : Not found

    !!! Ruboto setup is NOT OK !!!

Java JDK was not found.
Downloading...
Following redirect to https://edelivery.oracle.com/otn-pub/java/jdk/7/jdk-7-windows-x64.exe
Following redirect to http://download.oracle.com/errors/download-fail-1505220.html
Installing jdk-7-windows-x64.exe...
F, [2018-06-15T08:44:41.775056 #19372] FATAL -- : Unexpected exit code while installing Java: 127 (RuntimeError)
D:/Ruby24/lib/ruby/gems/2.4.0/gems/ruboto-1.6.1/lib/ruboto/util/setup.rb:383:in `install_java'
D:/Ruby24/lib/ruby/gems/2.4.0/gems/ruboto-1.6.1/lib/ruboto/util/setup.rb:301:in `install_all'
D:/Ruby24/lib/ruby/gems/2.4.0/gems/ruboto-1.6.1/lib/ruboto/util/setup.rb:24:in `setup_ruboto'
D:/Ruby24/lib/ruby/gems/2.4.0/gems/ruboto-1.6.1/lib/ruboto/commands/base.rb:472:in `run'
D:/Ruby24/lib/ruby/gems/2.4.0/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `block in run'
D:/Ruby24/lib/ruby/gems/2.4.0/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `catch'
D:/Ruby24/lib/ruby/gems/2.4.0/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `run'
D:/Ruby24/lib/ruby/gems/2.4.0/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
D:/Ruby24/lib/ruby/gems/2.4.0/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
D:/Ruby24/lib/ruby/gems/2.4.0/gems/ruboto-1.6.1/lib/ruboto/commands/base.rb:28:in `main'
D:/Ruby24/lib/ruby/gems/2.4.0/gems/ruboto-1.6.1/bin/ruboto:11:in `<top (required)>'
D:/Ruby24/bin/ruboto:23:in `load'
D:/Ruby24/bin/ruboto:23:in `<main>'

**Comment by donv** [comment]
The whole tooling of Ruboto needs to be updated since the underlying Android tooling has changed drastically.  This work has started, and any help is appreciated.

**Comment by ttych** [comment]
Same issue on Linux.

tools_r seem's to not be available anymore, and replaced by android-studio ?

when using android-studio, it setups the android sdk this way : 
```
SDK Components to Download: 
Android Emulator 191 MB
Android SDK Build-Tools 28.0.3 55.2 MB
Android SDK Platform 28 72.1 MB
Android SDK Platform-Tools 6.53 MB
Android SDK Tools 147 MB
Android Support Repository 339 MB
Google Repository 205 MB
SDK Patch Applier v4 1.74 MB
Sources for Android 28 40.6 MB
```

Android studio should be using a recipe : 
```
Downloading https://dl.google.com/android/repository/android_m2repository_r47.zip
Installing Android Support Repository in /home/thomas/local/Linux/x86_64/android-sdk/extras/android/m2repository
Downloading https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
Installing Android SDK Tools in /home/thomas/local/Linux/x86_64/android-sdk/tools
Downloading https://dl.google.com/android/repository/3534162-studio.sdk-patcher.zip.bak
Installing SDK Patch Applier v4 in /home/thomas/local/Linux/x86_64/android-sdk/patcher/v4
Downloading https://dl.google.com/android/repository/emulator-linux-4969155.zip
Installing Android Emulator in /home/thomas/local/Linux/x86_64/android-sdk/emulator
Downloading https://dl.google.com/android/repository/platform-28_r06.zip
Installing Android SDK Platform 28 in /home/thomas/local/Linux/x86_64/android-sdk/platforms/android-28
Downloading https://dl.google.com/android/repository/platform-tools_r28.0.1-linux.zip
Installing Android SDK Platform-Tools in /home/thomas/local/Linux/x86_64/android-sdk/platform-tools
Downloading https://dl.google.com/android/repository/sources-28_r01.zip
Installing Sources for Android 28 in /home/thomas/local/Linux/x86_64/android-sdk/sources/android-28
Downloading https://dl.google.com/android/repository/build-tools_r28.0.3-linux.zip
Installing Android SDK Build-Tools 28.0.3 in /home/thomas/local/Linux/x86_64/android-sdk/build-tools/28.0.3
Downloading https://dl.google.com/android/repository/google_m2repository_gms_v11_3_rc05_wear_2_0_5.zip
Installing Google Repository in /home/thomas/local/Linux/x86_64/android-sdk/extras/google/m2repository
```

@donv, I am available to test on Linux.
