### ISSUE TITLE
I had installed ruboto-core,app still ask me to install ruboto-core.

### ISSUE THREAD

**Issue by kematy** [ruboto/ruboto#851]
I had installed ruboto-core,app still ask me to install ruboto-core.I have no long path or white space in directory.why?

**Comment by kematy** [comment]
D:\Dev\test>rake
Picked up _JAVA_OPTIONS: -Xmx512M
ant.bat debug
Picked up _JAVA_OPTIONS: -Xmx512M
Buildfile: D:\Dev\test\build.xml
Trying to override old definition of task dex-helper

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 25.2.5
 [checkenv] Installed at D:\Dev\android-sdk-windows

-setup:
     [echo] Project Name: Test
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 23.0.1
     [echo] Resolving Build Target for Test...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: D:\Dev\test\bin\rsObj
    [mkdir] Created dir: D:\Dev\test\bin\rsLibs
     [echo] ----------
     [echo] Resolving Dependencies for Test...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency]
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] Found Deleted Target File
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Found Deleted Target File
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 2 source files to D:\Dev\test\bin\classes

-post-compile:

-obfuscate:

-dex:
     [echo] Picked up _JAVA_OPTIONS: -Xmx512M

-crunch:
   [crunch] Crunching PNG Files in source dir: D:\Dev\test\res
   [crunch] To destination dir: D:\Dev\test\bin\res
   [crunch] Processing image to cache: D:\Dev\test\res\drawable-hdpi\ic_launcher.png => D:\Dev\test\bin\res\drawable-hdpi\ic_launcher.png
   [crunch]   (processed image to cache entry D:\Dev\test\bin\res\drawable-hdpi\ic_launcher.png: 0% size of source)
   [crunch] Processing image to cache: D:\Dev\test\res\drawable-ldpi\ic_launcher.png => D:\Dev\test\bin\res\drawable-ldpi\ic_launcher.png
   [crunch]   (processed image to cache entry D:\Dev\test\bin\res\drawable-ldpi\ic_launcher.png: 0% size of source)
   [crunch] Processing image to cache: D:\Dev\test\res\drawable-mdpi\ic_launcher.png => D:\Dev\test\bin\res\drawable-mdpi\ic_launcher.png
   [crunch]   (processed image to cache entry D:\Dev\test\bin\res\drawable-mdpi\ic_launcher.png: 0% size of source)
   [crunch] Processing image to cache: D:\Dev\test\res\drawable-xhdpi\ic_launcher.png => D:\Dev\test\bin\res\drawable-xhdpi\ic_launcher.png
   [crunch]   (processed image to cache entry D:\Dev\test\bin\res\drawable-xhdpi\ic_launcher.png: 85% size of source)
   [crunch] Processing image to cache: D:\Dev\test\res\drawable\get_ruboto_core.png => D:\Dev\test\bin\res\drawable\get_ruboto_core.png
   [crunch]   (processed image to cache entry D:\Dev\test\bin\res\drawable\get_ruboto_core.png: 50% size of source)
   [crunch] Crunched 5 PNG files to update cache

-package-resources:
     [aapt] Creating full resource package...

-post-package-resources:

-package:
[apkbuilder] Current build type is different than previous build: forced apkbuilder run.
[apkbuilder] Creating Test-debug-unaligned.apk and signing it with a debug key...

-post-package:

-do-debug:
 [zipalign] Running zip align on final apk...
     [echo] Debug Package: D:\Dev\test\bin\Test-debug.apk
[propertyfile] Creating new property file: D:\Dev\test\bin\build.prop
[propertyfile] Updating property file: D:\Dev\test\bin\build.prop
[propertyfile] Updating property file: D:\Dev\test\bin\build.prop
[propertyfile] Updating property file: D:\Dev\test\bin\build.prop

-post-build:

debug:

BUILD SUCCESSFUL
Total time: 6 seconds

D:\Dev\test>

**Comment by donv** [comment]
Ruboto 2 now does not use the RubotoCore anymore.  All apps will be complete standalone apps.
