### ISSUE TITLE
Cannot generate new app

### ISSUE THREAD

**Issue by aonemd** [ruboto/ruboto#855]
Hello! I'm just starting out with ruboto and I have `ruboto setup` return OK for everything:

```
$ ruboto setup
/home/aonemd/.gem/ruby/2.6.2/gems/main-5.3.2/lib/main/getoptlong.rb:73: warning: constant ::FALSE is deprecated
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android SDK Manager      : Found
Android Emulator         : Found
Android SDK Command adb  : Found
nil versions are discouraged and will be deprecated in Rubygems 4
Android SDK Command dx   : Found
Platform SDK android-19  : Found

    *** Ruboto setup is OK! ***
```

however, when I try to generate a new app with the command in the README, I get an error message:

```
$ ruboto gen app --package com.yourdomain.whatever
/home/aonemd/.gem/ruby/2.6.2/gems/main-5.3.2/lib/main/getoptlong.rb:73: warning: constant ::FALSE is deprecated

Generating Android app Whatever in /home/aonemd/Workspace/whatever...
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "create project -n Whatever -t android-19 -p whatever -k com.yourdomain.whatever -a WhateverActivity"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
```

I also get the same error when I try to specify some arguments such as: `$ ruboto gen app --package com.mydomain.test --name Test --target android-19`.

**Comment by Ifiht** [comment]
@aonemd , I had the same problem. Your build-tools version is too new, the android command has not only been deprecated ([Google Ref](https://developer.android.com/studio/tools/help/android.html)), but at a certain point using it to create projects was also disabled. I had to downgrade my build-tools to 25.0.3, but even then once you do that the generated project doesn't seem to work. You can look at my example [here](https://github.com/Ifiht/jruby-env) to save yourself some trouble.

**Comment by aonemd** [comment]
Hey @Ifiht, thank you for your reply. I gave up on using ruboto since it seems a dead project anyway. There are more modern solutions available now to build for Android beside native of course.
