### ISSUE TITLE
Ruboto Core doesn't opening on Android 10

### ISSUE THREAD

**Issue by Sorunlu** [ruboto/ruboto#860]
Hi!

I installed Ruboto Core from ruboto.org. When i try to click on Ruboto Core, it returns "app is not responding". I need help about it.

My phone's specs;
-Brand: TECNO CE7j
-Helio G70 CPU x64
-6 GB RAM
-Android 10

**Comment by donv** [comment]
Ruboto Core is not in use anymore.  Creating Ruboto apps now uses the approach documented in https://github.com/ruboto/JRuby9K_POC
